-- Android Developer, HR Executive, HR Manager
WITH android_assessment AS (
  INSERT INTO assessments (
    title, description, category, difficulty, duration_minutes, passing_score,
    created_by, is_published, timer_enabled, grace_period_minutes, auto_submit_on_timeout,
    proctoring_enabled, face_detection_enabled, tab_switch_detection, max_tab_switches
  ) VALUES (
    'Android Developer',
    'Android development assessment covering Kotlin, Android architecture, UI/UX patterns, and mobile best practices',
    'Software Development',
    'medium',
    50,
    70,
    '391dea46-f9cc-43cc-a253-ae56151e8993',
    true,
    true,
    5,
    true,
    true,
    true,
    true,
    3
  )
  RETURNING id
),
android_questions AS (
  INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, order_index, points)
  SELECT 
    id,
    unnest(ARRAY[
      'What is the primary language for Android development?',
      'What is an Activity in Android?',
      'What is the purpose of AndroidManifest.xml?',
      'What is a Fragment in Android?',
      'How do you handle background tasks in Android?',
      'What is RecyclerView used for?',
      'What is the Android lifecycle?',
      'How do you persist data in Android?',
      'What is Material Design?',
      'What is the purpose of Intent?',
      'What is ViewModel in MVVM?',
      'How do you implement navigation in Android?',
      'What is Room database?',
      'What is Retrofit used for?',
      'What is the purpose of Gradle?',
      'What is dependency injection in Android?',
      'What is LiveData?',
      'How do you handle permissions in Android?',
      'What is Jetpack Compose?',
      'What is coroutines in Kotlin?'
    ]),
    'multiple_choice',
    unnest(ARRAY[
      '["Kotlin", "Swift", "Python", "JavaScript"]'::jsonb,
      '["A screen/UI component", "A database", "A network call", "A file"]'::jsonb,
      '["Declare app components and permissions", "Store data", "Handle UI", "Run code"]'::jsonb,
      '["Reusable UI portion of Activity", "Database table", "Network request", "File type"]'::jsonb,
      '["WorkManager, Services, Coroutines", "Main thread only", "No background tasks", "Activities"]'::jsonb,
      '["Display scrolling lists efficiently", "Database", "Network calls", "Permissions"]'::jsonb,
      '["Series of states from creation to destruction", "Database schema", "Network protocol", "File system"]'::jsonb,
      '["SharedPreferences, Room, Files", "Only memory", "Only cloud", "No persistence"]'::jsonb,
      '["Google UI design system", "Database", "Programming language", "Testing framework"]'::jsonb,
      '["Start activities and pass data", "Store data", "Display UI", "Handle network"]'::jsonb,
      '["Hold and manage UI data", "Display views", "Handle network", "Store files"]'::jsonb,
      '["Navigation Component", "Manual intents", "No navigation", "Web views"]'::jsonb,
      '["Local SQLite database abstraction", "Cloud storage", "File system", "Network library"]'::jsonb,
      '["HTTP client for API calls", "Database", "UI framework", "Testing tool"]'::jsonb,
      '["Build automation tool", "Database", "UI framework", "Runtime"]'::jsonb,
      '["Provide dependencies automatically", "Database query", "UI rendering", "Network call"]'::jsonb,
      '["Observable data holder", "Database", "Network client", "File manager"]'::jsonb,
      '["Request at runtime for dangerous permissions", "Automatic grant", "No permissions", "Compile time"]'::jsonb,
      '["Modern declarative UI toolkit", "Database", "Network library", "Testing framework"]'::jsonb,
      '["Asynchronous programming", "Database queries", "UI rendering", "File operations"]'::jsonb
    ]),
    unnest(ARRAY[
      'Kotlin',
      'A screen/UI component',
      'Declare app components and permissions',
      'Reusable UI portion of Activity',
      'WorkManager, Services, Coroutines',
      'Display scrolling lists efficiently',
      'Series of states from creation to destruction',
      'SharedPreferences, Room, Files',
      'Google UI design system',
      'Start activities and pass data',
      'Hold and manage UI data',
      'Navigation Component',
      'Local SQLite database abstraction',
      'HTTP client for API calls',
      'Build automation tool',
      'Provide dependencies automatically',
      'Observable data holder',
      'Request at runtime for dangerous permissions',
      'Modern declarative UI toolkit',
      'Asynchronous programming'
    ]),
    generate_series(1, 20),
    5
  FROM android_assessment
  RETURNING 1
),
hr_exec_assessment AS (
  INSERT INTO assessments (
    title, description, category, difficulty, duration_minutes, passing_score,
    created_by, is_published, timer_enabled, grace_period_minutes, auto_submit_on_timeout,
    proctoring_enabled, face_detection_enabled, tab_switch_detection, max_tab_switches
  ) VALUES (
    'HR Executive - Recruitment',
    'HR recruitment assessment covering talent acquisition, candidate screening, employer branding, and recruitment strategies',
    'Human Resources',
    'easy',
    45,
    70,
    '391dea46-f9cc-43cc-a253-ae56151e8993',
    true,
    true,
    5,
    true,
    false,
    false,
    true,
    5
  )
  RETURNING id
),
hr_exec_questions AS (
  INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, order_index, points)
  SELECT 
    id,
    unnest(ARRAY[
      'What is talent acquisition?',
      'What is the purpose of job description?',
      'How do you screen candidates effectively?',
      'What is employer branding?',
      'What are the stages of recruitment?',
      'How do you assess cultural fit?',
      'What is candidate experience?',
      'What is an applicant tracking system?',
      'How do you source candidates?',
      'What is behavioral interviewing?',
      'What is time-to-hire metric?',
      'How do you conduct reference checks?',
      'What is diversity hiring?',
      'What is onboarding process?',
      'How do you negotiate job offers?',
      'What is passive candidate?',
      'What is Boolean search in recruitment?',
      'What is headhunting?',
      'How do you measure recruitment success?',
      'What is talent pipeline?'
    ]),
    'multiple_choice',
    unnest(ARRAY[
      '["Strategic approach to finding talent", "Just posting jobs", "Only internal hiring", "Random selection"]'::jsonb,
      '["Define role requirements and responsibilities", "Formality only", "Not important", "Legal requirement"]'::jsonb,
      '["Resume review, skills assessment, interviews", "Random selection", "First come first serve", "No screening"]'::jsonb,
      '["Company reputation as an employer", "Product branding", "Logo design", "Website"]'::jsonb,
      '["Sourcing, screening, interviewing, offer, onboarding", "Just interviewing", "Only posting", "No stages"]'::jsonb,
      '["Values alignment and behavioral questions", "Technical skills only", "Random questions", "No assessment"]'::jsonb,
      '["Candidate journey through hiring process", "Technical test", "Salary negotiation", "Exit interview"]'::jsonb,
      '["Software to manage recruitment", "Database", "Email client", "Calendar"]'::jsonb,
      '["Job boards, LinkedIn, referrals, agencies", "Single source only", "Random search", "No sourcing"]'::jsonb,
      '["Questions about past behavior and situations", "Technical questions", "Math problems", "General knowledge"]'::jsonb,
      '["Time from posting to offer acceptance", "Working hours", "Training time", "Contract length"]'::jsonb,
      '["Contact previous employers for feedback", "Skip this step", "Social media check", "Random calls"]'::jsonb,
      '["Inclusive hiring for diverse candidates", "Only one type of hire", "Random selection", "No diversity"]'::jsonb,
      '["Integrating new hires into organization", "Just first day", "Training only", "Documentation"]'::jsonb,
      '["Discuss compensation and benefits", "Take it or leave it", "No negotiation", "HR decides all"]'::jsonb,
      '["Not actively looking but open to opportunities", "Unemployed", "Active jobseeker", "Retired"]'::jsonb,
      '["Advanced search using operators", "Random search", "Manual review", "No search"]'::jsonb,
      '["Proactive candidate search for specific roles", "Posting jobs", "Waiting for applications", "Random calls"]'::jsonb,
      '["Quality of hire, time-to-fill, cost-per-hire", "Number of interviews", "Coffee consumed", "No measurement"]'::jsonb,
      '["Pool of qualified candidates for future roles", "Current employees", "Rejected candidates", "No pipeline"]'::jsonb
    ]),
    unnest(ARRAY[
      'Strategic approach to finding talent',
      'Define role requirements and responsibilities',
      'Resume review, skills assessment, interviews',
      'Company reputation as an employer',
      'Sourcing, screening, interviewing, offer, onboarding',
      'Values alignment and behavioral questions',
      'Candidate journey through hiring process',
      'Software to manage recruitment',
      'Job boards, LinkedIn, referrals, agencies',
      'Questions about past behavior and situations',
      'Time from posting to offer acceptance',
      'Contact previous employers for feedback',
      'Inclusive hiring for diverse candidates',
      'Integrating new hires into organization',
      'Discuss compensation and benefits',
      'Not actively looking but open to opportunities',
      'Advanced search using operators',
      'Proactive candidate search for specific roles',
      'Quality of hire, time-to-fill, cost-per-hire',
      'Pool of qualified candidates for future roles'
    ]),
    generate_series(1, 20),
    4
  FROM hr_exec_assessment
  RETURNING 1
),
hr_manager_assessment AS (
  INSERT INTO assessments (
    title, description, category, difficulty, duration_minutes, passing_score,
    created_by, is_published, timer_enabled, grace_period_minutes, auto_submit_on_timeout,
    proctoring_enabled, face_detection_enabled, tab_switch_detection, max_tab_switches
  ) VALUES (
    'HR Manager - Generalist',
    'Comprehensive HR management assessment covering employee relations, performance management, and HR operations',
    'Human Resources',
    'medium',
    60,
    70,
    '391dea46-f9cc-43cc-a253-ae56151e8993',
    true,
    true,
    5,
    true,
    false,
    false,
    true,
    5
  )
  RETURNING id
)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, order_index, points)
SELECT 
  id,
  unnest(ARRAY[
    'What is employee relations?',
    'What is performance management?',
    'How do you handle employee conflicts?',
    'What is HR compliance?',
    'What is employee engagement?',
    'How do you conduct performance reviews?',
    'What is succession planning?',
    'What is HR analytics?',
    'How do you manage workplace diversity?',
    'What is organizational development?',
    'What is change management in HR?',
    'How do you handle disciplinary actions?',
    'What is talent management?',
    'What is workforce planning?',
    'How do you measure employee satisfaction?',
    'What is learning and development?',
    'What is compensation strategy?',
    'How do you implement HR policies?',
    'What is employee retention?',
    'What is HR technology?'
  ]),
  'multiple_choice',
  unnest(ARRAY[
    '["Managing employee-employer relationship", "Hiring only", "Payroll", "IT support"]'::jsonb,
    '["Setting goals and evaluating performance", "Hiring process", "Payroll", "Leave management"]'::jsonb,
    '["Mediation, investigation, resolution", "Ignore them", "Fire everyone", "Random decision"]'::jsonb,
    '["Following labor laws and regulations", "Optional guidelines", "No compliance needed", "Internal rules only"]'::jsonb,
    '["Employee commitment and motivation", "Just presence", "Clock in/out", "Salary only"]'::jsonb,
    '["Regular feedback and goal assessment", "Once a year formality", "Never review", "Random comments"]'::jsonb,
    '["Identifying and developing future leaders", "Firing plan", "Retirement only", "No planning"]'::jsonb,
    '["Using data for HR decisions", "Guessing", "Random choices", "No analysis"]'::jsonb,
    '["Inclusive policies and practices", "Single culture", "No diversity", "Random approach"]'::jsonb,
    '["Improving organizational effectiveness", "Just hiring", "IT infrastructure", "Building maintenance"]'::jsonb,
    '["Managing organizational transitions", "Resistance only", "No change", "Random changes"]'::jsonb,
    '["Fair process with documentation", "Random punishment", "No process", "Manager decides"]'::jsonb,
    '["Attracting, developing, retaining talent", "Hiring only", "Training only", "Payroll"]'::jsonb,
    '["Forecasting workforce needs", "Random hiring", "No planning", "Wait for vacancies"]'::jsonb,
    '["Surveys, feedback, retention rates", "Guessing", "No measurement", "Manager opinion"]'::jsonb,
    '["Training and skill development programs", "No training", "Self-study only", "Random workshops"]'::jsonb,
    '["Rewarding employees competitively", "Minimum wage only", "Random salaries", "No strategy"]'::jsonb,
    '["Communication, training, enforcement", "Just write them", "Email only", "No implementation"]'::jsonb,
    '["Keeping valuable employees", "High turnover", "No retention effort", "Fire and rehire"]'::jsonb,
    '["Software and systems for HR management", "Paper only", "No technology", "IT department"]'::jsonb
  ]),
  unnest(ARRAY[
    'Managing employee-employer relationship',
    'Setting goals and evaluating performance',
    'Mediation, investigation, resolution',
    'Following labor laws and regulations',
    'Employee commitment and motivation',
    'Regular feedback and goal assessment',
    'Identifying and developing future leaders',
    'Using data for HR decisions',
    'Inclusive policies and practices',
    'Improving organizational effectiveness',
    'Managing organizational transitions',
    'Fair process with documentation',
    'Attracting, developing, retaining talent',
    'Forecasting workforce needs',
    'Surveys, feedback, retention rates',
    'Training and skill development programs',
    'Rewarding employees competitively',
    'Communication, training, enforcement',
    'Keeping valuable employees',
    'Software and systems for HR management'
  ]),
  generate_series(1, 20),
  5
FROM hr_manager_assessment;