-- Backend Developer (Node.js)
WITH backend_assessment AS (
  INSERT INTO assessments (
    title, description, category, difficulty, duration_minutes, passing_score,
    created_by, is_published, timer_enabled, grace_period_minutes, auto_submit_on_timeout,
    proctoring_enabled, face_detection_enabled, tab_switch_detection, max_tab_switches
  ) VALUES (
    'Backend Developer (Node.js)',
    'In-depth Node.js assessment covering Express.js, database design, REST APIs, and security best practices',
    'Software Development',
    'medium',
    60,
    70,
    '391dea46-f9cc-43cc-a253-ae56151e8993',
    true,
    true,
    5,
    true,
    true,
    true,
    true,
    3
  )
  RETURNING id
)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, order_index, points)
SELECT 
  id,
  unnest(ARRAY[
    'What is Node.js built on?',
    'Which module is used to create a web server in Node.js?',
    'What is middleware in Express.js?',
    'How do you handle asynchronous operations in Node.js?',
    'What is the purpose of package.json?',
    'Which HTTP method is used to update a resource?',
    'What is JWT used for?',
    'How do you prevent SQL injection?',
    'What is the purpose of clustering in Node.js?',
    'Which database is NoSQL?',
    'What is RESTful API?',
    'How do you handle errors in Express.js?',
    'What is CORS?',
    'Which status code indicates success?',
    'What is the purpose of environment variables?',
    'How do you secure API endpoints?',
    'What is the difference between SQL and NoSQL?',
    'What is connection pooling?',
    'How do you implement rate limiting?',
    'What is the purpose of indexing in databases?',
    'What is bcrypt used for?',
    'How do you handle file uploads?',
    'What is the purpose of ORM?',
    'What is API versioning?',
    'How do you implement authentication?'
  ]),
  'multiple_choice',
  unnest(ARRAY[
    '["V8 JavaScript engine", "Python", "Java", "Ruby"]'::jsonb,
    '["http", "fs", "path", "url"]'::jsonb,
    '["Functions that process requests", "Database queries", "Frontend components", "Test cases"]'::jsonb,
    '["Promises and async/await", "Callbacks only", "Synchronous code", "Multithreading"]'::jsonb,
    '["Manage project dependencies", "Store data", "Run tests", "Deploy application"]'::jsonb,
    '["PUT or PATCH", "GET", "DELETE", "POST"]'::jsonb,
    '["Authentication tokens", "Encryption", "Database queries", "File storage"]'::jsonb,
    '["Parameterized queries", "String concatenation", "Direct queries", "No prevention needed"]'::jsonb,
    '["Scale across CPU cores", "Store data", "Handle requests", "Compile code"]'::jsonb,
    '["MongoDB", "MySQL", "PostgreSQL", "SQLite"]'::jsonb,
    '["Architectural style for APIs", "Database type", "Programming language", "Testing framework"]'::jsonb,
    '["Error handling middleware", "try-catch only", "Ignore errors", "Log to console"]'::jsonb,
    '["Cross-Origin Resource Sharing", "Database connection", "File system", "Authentication"]'::jsonb,
    '["200", "404", "500", "401"]'::jsonb,
    '["Store configuration securely", "Store user data", "Cache responses", "Log errors"]'::jsonb,
    '["Authentication and authorization", "Public access only", "No security needed", "CORS only"]'::jsonb,
    '["Schema vs schemaless", "Speed only", "Both are same", "Location"]'::jsonb,
    '["Reuse database connections", "Store pool data", "Create backups", "Monitor performance"]'::jsonb,
    '["Middleware or packages", "Database queries", "Frontend code", "No implementation needed"]'::jsonb,
    '["Improve query performance", "Store more data", "Backup data", "Encrypt data"]'::jsonb,
    '["Hash passwords", "Store passwords", "Send passwords", "Validate emails"]'::jsonb,
    '["Multer or similar middleware", "Direct file system", "Database only", "Not possible"]'::jsonb,
    '["Object-Relational Mapping", "File storage", "Authentication", "Caching"]'::jsonb,
    '["Managing API changes", "Deleting APIs", "Creating databases", "Frontend routing"]'::jsonb,
    '["JWT, sessions, OAuth", "Cookies only", "No authentication", "Basic auth only"]'::jsonb
  ]),
  unnest(ARRAY[
    'V8 JavaScript engine',
    'http',
    'Functions that process requests',
    'Promises and async/await',
    'Manage project dependencies',
    'PUT or PATCH',
    'Authentication tokens',
    'Parameterized queries',
    'Scale across CPU cores',
    'MongoDB',
    'Architectural style for APIs',
    'Error handling middleware',
    'Cross-Origin Resource Sharing',
    '200',
    'Store configuration securely',
    'Authentication and authorization',
    'Schema vs schemaless',
    'Reuse database connections',
    'Middleware or packages',
    'Improve query performance',
    'Hash passwords',
    'Multer or similar middleware',
    'Object-Relational Mapping',
    'Managing API changes',
    'JWT, sessions, OAuth'
  ]),
  generate_series(1, 25),
  4
FROM backend_assessment;