
-- ================================================
-- SEED 17 NEW ASSESSMENTS across Finance, Healthcare, Pharmacy, Accounting, Banking, Sales, Data/Analytics, Customer Support
-- ================================================

-- Use existing admin user as creator
DO $$
DECLARE
  admin_id uuid := '391dea46-f9cc-43cc-a253-ae56151e8993';
  
  -- Assessment IDs
  a_finance_fund uuid := gen_random_uuid();
  a_finance_risk uuid := gen_random_uuid();
  a_finance_invest uuid := gen_random_uuid();
  a_healthcare_gen uuid := gen_random_uuid();
  a_healthcare_admin uuid := gen_random_uuid();
  a_pharmacy_tech uuid := gen_random_uuid();
  a_pharmacy_mgmt uuid := gen_random_uuid();
  a_accounting_basic uuid := gen_random_uuid();
  a_accounting_adv uuid := gen_random_uuid();
  a_banking_ops uuid := gen_random_uuid();
  a_banking_compliance uuid := gen_random_uuid();
  a_sales_gen uuid := gen_random_uuid();
  a_sales_b2b uuid := gen_random_uuid();
  a_data_analyst uuid := gen_random_uuid();
  a_data_engineer uuid := gen_random_uuid();
  a_cs_support uuid := gen_random_uuid();
  a_hr_talent uuid := gen_random_uuid();
  
BEGIN

-- ===== INSERT 17 ASSESSMENTS =====
INSERT INTO assessments (id, title, description, category, difficulty, duration_minutes, passing_score, created_by, is_published) VALUES
(a_finance_fund, 'Finance Fundamentals', 'Core finance concepts including time value of money, financial statements, and basic valuation.', 'Finance', 'easy', 30, 65, admin_id, true),
(a_finance_risk, 'Financial Risk Management', 'Advanced risk assessment, portfolio theory, derivatives, and hedging strategies.', 'Finance', 'hard', 45, 70, admin_id, true),
(a_finance_invest, 'Investment Analysis & Portfolio Management', 'Equity valuation, bond pricing, portfolio optimization, and market efficiency.', 'Finance', 'medium', 40, 65, admin_id, true),
(a_healthcare_gen, 'Healthcare Administration', 'Healthcare systems, patient management, regulatory compliance, and quality assurance.', 'Healthcare', 'medium', 35, 65, admin_id, true),
(a_healthcare_admin, 'Clinical Operations Management', 'Clinical workflows, EMR systems, patient safety protocols, and healthcare analytics.', 'Healthcare', 'hard', 40, 70, admin_id, true),
(a_pharmacy_tech, 'Pharmacy Technician Essentials', 'Pharmaceutical calculations, drug classifications, dispensing procedures, and safety protocols.', 'Pharmacy', 'easy', 30, 65, admin_id, true),
(a_pharmacy_mgmt, 'Pharmacy Management & Compliance', 'Pharmacy operations, regulatory compliance, inventory management, and patient counseling.', 'Pharmacy', 'medium', 35, 70, admin_id, true),
(a_accounting_basic, 'Accounting Fundamentals', 'Double-entry bookkeeping, financial statements, GAAP principles, and basic audit concepts.', 'Accounting', 'easy', 30, 65, admin_id, true),
(a_accounting_adv, 'Advanced Accounting & Taxation', 'Corporate taxation, consolidation, IFRS/GAAP differences, and forensic accounting.', 'Accounting', 'hard', 45, 70, admin_id, true),
(a_banking_ops, 'Banking Operations', 'Core banking systems, payment processing, credit analysis, and customer onboarding.', 'Banking', 'medium', 35, 65, admin_id, true),
(a_banking_compliance, 'Banking Compliance & AML', 'Anti-money laundering, KYC procedures, regulatory frameworks, and risk-based approaches.', 'Banking', 'hard', 40, 70, admin_id, true),
(a_sales_gen, 'Sales Fundamentals & CRM', 'Sales methodologies, CRM usage, pipeline management, and negotiation techniques.', 'Sales & Marketing', 'easy', 30, 65, admin_id, true),
(a_sales_b2b, 'B2B Sales & Enterprise Selling', 'Enterprise sales cycles, stakeholder management, solution selling, and account-based strategies.', 'Sales & Marketing', 'medium', 35, 70, admin_id, true),
(a_data_analyst, 'Data Analyst Assessment', 'SQL queries, data visualization, statistical analysis, and business intelligence tools.', 'Data & Analytics', 'medium', 40, 65, admin_id, true),
(a_data_engineer, 'Data Engineering Fundamentals', 'ETL pipelines, data warehousing, cloud data platforms, and big data technologies.', 'Data & Analytics', 'hard', 45, 70, admin_id, true),
(a_cs_support, 'Customer Support Excellence', 'Customer service principles, conflict resolution, SLA management, and support tools.', 'Customer Support', 'easy', 25, 65, admin_id, true),
(a_hr_talent, 'Talent Acquisition Specialist', 'Sourcing strategies, interviewing techniques, employer branding, and recruitment metrics.', 'Human Resources', 'medium', 35, 65, admin_id, true);

-- ===== INSERT QUESTIONS FOR EACH ASSESSMENT (20 per test) =====

-- FINANCE FUNDAMENTALS (20 questions)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, points, order_index) VALUES
(a_finance_fund, 'What is the time value of money?', 'multiple_choice', '["Money available now is worth more than the same amount in the future","Money in the future is always worth more","Time has no effect on money value","It only applies to investments"]', 'Money available now is worth more than the same amount in the future', 5, 1),
(a_finance_fund, 'Which financial statement shows a company''s revenues and expenses?', 'multiple_choice', '["Balance Sheet","Income Statement","Cash Flow Statement","Statement of Equity"]', 'Income Statement', 5, 2),
(a_finance_fund, 'What does ROI stand for?', 'multiple_choice', '["Return on Investment","Rate of Interest","Revenue over Income","Return on Insurance"]', 'Return on Investment', 5, 3),
(a_finance_fund, 'A current ratio above 1 indicates:', 'multiple_choice', '["More current assets than current liabilities","The company is bankrupt","High long-term debt","Low profitability"]', 'More current assets than current liabilities', 5, 4),
(a_finance_fund, 'What is the formula for Net Income?', 'multiple_choice', '["Revenue - Expenses","Assets - Liabilities","Revenue + Expenses","Cash In - Cash Out"]', 'Revenue - Expenses', 5, 5),
(a_finance_fund, 'Which is NOT a type of financial market?', 'multiple_choice', '["Stock Market","Bond Market","Resource Market","Human Capital Market"]', 'Human Capital Market', 5, 6),
(a_finance_fund, 'What does EBITDA stand for?', 'multiple_choice', '["Earnings Before Interest, Taxes, Depreciation, and Amortization","Earnings Before Internal Tax Deductions Applied","Estimated Business Income Tax Deduction Amount","None of the above"]', 'Earnings Before Interest, Taxes, Depreciation, and Amortization', 5, 7),
(a_finance_fund, 'What is compound interest?', 'multiple_choice', '["Interest calculated on initial principal only","Interest calculated on principal plus accumulated interest","A type of tax","A banking fee"]', 'Interest calculated on principal plus accumulated interest', 5, 8),
(a_finance_fund, 'The debt-to-equity ratio measures:', 'multiple_choice', '["Financial leverage","Profitability","Liquidity","Market value"]', 'Financial leverage', 5, 9),
(a_finance_fund, 'Which is a source of equity financing?', 'multiple_choice', '["Bank loan","Corporate bond","Issuing shares","Trade credit"]', 'Issuing shares', 5, 10),
(a_finance_fund, 'What is a balance sheet?', 'multiple_choice', '["A snapshot of financial position at a point in time","A record of all transactions","A list of employees","A tax document"]', 'A snapshot of financial position at a point in time', 5, 11),
(a_finance_fund, 'Working capital is calculated as:', 'multiple_choice', '["Current Assets - Current Liabilities","Total Assets - Total Liabilities","Revenue - COGS","Net Income - Dividends"]', 'Current Assets - Current Liabilities', 5, 12),
(a_finance_fund, 'What is depreciation?', 'multiple_choice', '["Allocation of asset cost over its useful life","Increase in asset value","A type of tax","Interest on debt"]', 'Allocation of asset cost over its useful life', 5, 13),
(a_finance_fund, 'NPV stands for:', 'multiple_choice', '["Net Present Value","Net Profit Value","New Portfolio Value","None of these"]', 'Net Present Value', 5, 14),
(a_finance_fund, 'Which ratio measures how quickly inventory is sold?', 'multiple_choice', '["Inventory Turnover","Current Ratio","Quick Ratio","Debt Ratio"]', 'Inventory Turnover', 5, 15),
(a_finance_fund, 'A bond''s face value is also called:', 'multiple_choice', '["Par value","Market value","Book value","Intrinsic value"]', 'Par value', 5, 16),
(a_finance_fund, 'What is liquidity?', 'multiple_choice', '["Ability to convert assets to cash quickly","Total amount of debt","Annual profit margin","Stock price volatility"]', 'Ability to convert assets to cash quickly', 5, 17),
(a_finance_fund, 'The P/E ratio compares:', 'multiple_choice', '["Price to Earnings","Profit to Expenses","Principal to Equity","Performance to Efficiency"]', 'Price to Earnings', 5, 18),
(a_finance_fund, 'What is diversification?', 'multiple_choice', '["Spreading investments to reduce risk","Investing in one stock","Taking on more debt","Reducing expenses"]', 'Spreading investments to reduce risk', 5, 19),
(a_finance_fund, 'Operating cash flow measures:', 'multiple_choice', '["Cash generated from core business operations","Total company value","Stock market performance","Employee productivity"]', 'Cash generated from core business operations', 5, 20),

-- FINANCIAL RISK MANAGEMENT (20 questions)
(a_finance_risk, 'Value at Risk (VaR) measures:', 'multiple_choice', '["Maximum potential loss over a given time period at a confidence level","Average return on investment","Total portfolio value","Minimum required return"]', 'Maximum potential loss over a given time period at a confidence level', 5, 1),
(a_finance_risk, 'Which is NOT a type of financial risk?', 'multiple_choice', '["Market Risk","Credit Risk","Operational Risk","Motivational Risk"]', 'Motivational Risk', 5, 2),
(a_finance_risk, 'A call option gives the holder the right to:', 'multiple_choice', '["Buy an asset at a specified price","Sell an asset at a specified price","Borrow money","Issue bonds"]', 'Buy an asset at a specified price', 5, 3),
(a_finance_risk, 'What is Beta in portfolio theory?', 'multiple_choice', '["Measure of systematic risk relative to the market","Total return","Dividend yield","Book value ratio"]', 'Measure of systematic risk relative to the market', 5, 4),
(a_finance_risk, 'Hedging is used to:', 'multiple_choice', '["Reduce exposure to risk","Increase leverage","Maximize returns","Avoid taxes"]', 'Reduce exposure to risk', 5, 5),
(a_finance_risk, 'The Sharpe Ratio measures:', 'multiple_choice', '["Risk-adjusted return","Total risk","Market capitalization","Dividend payout"]', 'Risk-adjusted return', 5, 6),
(a_finance_risk, 'What is counterparty risk?', 'multiple_choice', '["Risk that the other party defaults on obligations","Risk of market crash","Currency fluctuation risk","Inflation risk"]', 'Risk that the other party defaults on obligations', 5, 7),
(a_finance_risk, 'Monte Carlo simulation is used for:', 'multiple_choice', '["Modeling probability of different outcomes","Calculating simple interest","Balancing budgets","Filing taxes"]', 'Modeling probability of different outcomes', 5, 8),
(a_finance_risk, 'What is a credit default swap?', 'multiple_choice', '["A derivative that transfers credit risk","A type of stock","A bank account","A government bond"]', 'A derivative that transfers credit risk', 5, 9),
(a_finance_risk, 'Stress testing in finance involves:', 'multiple_choice', '["Evaluating performance under extreme scenarios","Testing employee resilience","Checking system uptime","Auditing financial records"]', 'Evaluating performance under extreme scenarios', 5, 10),
(a_finance_risk, 'What is operational risk?', 'multiple_choice', '["Risk of loss from failed internal processes or systems","Stock price volatility","Interest rate changes","Currency fluctuations"]', 'Risk of loss from failed internal processes or systems', 5, 11),
(a_finance_risk, 'The Black-Scholes model is used to price:', 'multiple_choice', '["Options","Bonds","Stocks","Real estate"]', 'Options', 5, 12),
(a_finance_risk, 'What is a risk matrix?', 'multiple_choice', '["A tool that plots likelihood vs impact of risks","A financial statement","A trading platform","An insurance policy"]', 'A tool that plots likelihood vs impact of risks', 5, 13),
(a_finance_risk, 'Correlation of -1 between two assets means:', 'multiple_choice', '["They move in exactly opposite directions","They move together","No relationship","Same volatility"]', 'They move in exactly opposite directions', 5, 14),
(a_finance_risk, 'What is liquidity risk?', 'multiple_choice', '["Risk of not being able to sell an asset quickly at fair price","Risk of inflation","Risk of default","Risk of fraud"]', 'Risk of not being able to sell an asset quickly at fair price', 5, 15),
(a_finance_risk, 'Basel III primarily addresses:', 'multiple_choice', '["Bank capital requirements and risk management","Tax regulations","Employment law","Environmental standards"]', 'Bank capital requirements and risk management', 5, 16),
(a_finance_risk, 'A put option gives the right to:', 'multiple_choice', '["Sell at a specified price","Buy at a specified price","Lend money","Issue equity"]', 'Sell at a specified price', 5, 17),
(a_finance_risk, 'Expected shortfall (CVaR) differs from VaR by:', 'multiple_choice', '["Measuring average loss beyond VaR threshold","Being always smaller","Ignoring tail risk","Only using historical data"]', 'Measuring average loss beyond VaR threshold', 5, 18),
(a_finance_risk, 'What is mark-to-market?', 'multiple_choice', '["Valuing assets at current market price","Setting a target price","Marketing strategy","Benchmark analysis"]', 'Valuing assets at current market price', 5, 19),
(a_finance_risk, 'Duration in bond analysis measures:', 'multiple_choice', '["Sensitivity of bond price to interest rate changes","Time to maturity only","Coupon rate","Credit quality"]', 'Sensitivity of bond price to interest rate changes', 5, 20),

-- HEALTHCARE ADMINISTRATION (20 questions)
(a_healthcare_gen, 'HIPAA primarily protects:', 'multiple_choice', '["Patient health information privacy","Hospital finances","Doctor salaries","Medical equipment"]', 'Patient health information privacy', 5, 1),
(a_healthcare_gen, 'EMR stands for:', 'multiple_choice', '["Electronic Medical Record","Emergency Medical Response","Extended Medical Review","Electronic Medication Registry"]', 'Electronic Medical Record', 5, 2),
(a_healthcare_gen, 'What is patient throughput?', 'multiple_choice', '["Rate at which patients move through a healthcare facility","Number of beds","Staff count","Revenue per patient"]', 'Rate at which patients move through a healthcare facility', 5, 3),
(a_healthcare_gen, 'Which agency accredits hospitals in the US?', 'multiple_choice', '["The Joint Commission","FDA","CDC","WHO"]', 'The Joint Commission', 5, 4),
(a_healthcare_gen, 'DRG stands for:', 'multiple_choice', '["Diagnosis Related Group","Doctor Review Guide","Drug Regulation Group","Direct Revenue Generator"]', 'Diagnosis Related Group', 5, 5),
(a_healthcare_gen, 'What is a formulary?', 'multiple_choice', '["A list of approved medications","A medical form","A formula for dosage","A patient record"]', 'A list of approved medications', 5, 6),
(a_healthcare_gen, 'Patient satisfaction scores are commonly measured by:', 'multiple_choice', '["HCAHPS surveys","Blood tests","Staff reviews","Financial audits"]', 'HCAHPS surveys', 5, 7),
(a_healthcare_gen, 'What is population health management?', 'multiple_choice', '["Managing health outcomes of a defined group","Treating individual patients","Hospital construction","Drug manufacturing"]', 'Managing health outcomes of a defined group', 5, 8),
(a_healthcare_gen, 'ICD-10 is used for:', 'multiple_choice', '["Medical coding and classification of diseases","Patient scheduling","Staff management","Equipment tracking"]', 'Medical coding and classification of diseases', 5, 9),
(a_healthcare_gen, 'What is healthcare utilization review?', 'multiple_choice', '["Evaluating necessity and appropriateness of medical services","Counting patients","Reviewing staff performance","Auditing finances"]', 'Evaluating necessity and appropriateness of medical services', 5, 10),
(a_healthcare_gen, 'Telemedicine is:', 'multiple_choice', '["Remote delivery of healthcare services via technology","A type of surgery","Hospital management software","An insurance plan"]', 'Remote delivery of healthcare services via technology', 5, 11),
(a_healthcare_gen, 'What does CMS stand for in US healthcare?', 'multiple_choice', '["Centers for Medicare & Medicaid Services","Central Medical System","Clinical Management Software","Care Monitoring Service"]', 'Centers for Medicare & Medicaid Services', 5, 12),
(a_healthcare_gen, 'A sentinel event is:', 'multiple_choice', '["An unexpected occurrence involving death or serious harm","A scheduled procedure","A routine checkup","A billing code"]', 'An unexpected occurrence involving death or serious harm', 5, 13),
(a_healthcare_gen, 'What is value-based care?', 'multiple_choice', '["Reimbursement based on patient outcomes rather than volume","Cheapest care possible","Most expensive treatment","Only emergency care"]', 'Reimbursement based on patient outcomes rather than volume', 5, 14),
(a_healthcare_gen, 'CPT codes are used for:', 'multiple_choice', '["Billing medical procedures","Patient identification","Drug classification","Facility licensing"]', 'Billing medical procedures', 5, 15),
(a_healthcare_gen, 'What is a clinical pathway?', 'multiple_choice', '["Standardized care plan for a specific condition","Hospital hallway","Career path in medicine","Drug delivery route"]', 'Standardized care plan for a specific condition', 5, 16),
(a_healthcare_gen, 'Healthcare quality is commonly measured by:', 'multiple_choice', '["Structure, Process, and Outcome metrics","Revenue only","Number of doctors","Building size"]', 'Structure, Process, and Outcome metrics', 5, 17),
(a_healthcare_gen, 'What is care coordination?', 'multiple_choice', '["Organizing patient care across providers and settings","Scheduling staff shifts","Managing equipment","Processing payments"]', 'Organizing patient care across providers and settings', 5, 18),
(a_healthcare_gen, 'What does LOS stand for in healthcare?', 'multiple_choice', '["Length of Stay","Level of Service","List of Symptoms","License of Surgery"]', 'Length of Stay', 5, 19),
(a_healthcare_gen, 'Informed consent requires:', 'multiple_choice', '["Patient understanding risks, benefits, and alternatives","Just a signature","Doctor approval only","Insurance verification"]', 'Patient understanding risks, benefits, and alternatives', 5, 20),

-- ACCOUNTING FUNDAMENTALS (20 questions)
(a_accounting_basic, 'The accounting equation is:', 'multiple_choice', '["Assets = Liabilities + Equity","Revenue = Expenses + Profit","Cash = Income - Costs","Debt = Credit + Debit"]', 'Assets = Liabilities + Equity', 5, 1),
(a_accounting_basic, 'Which is a current asset?', 'multiple_choice', '["Accounts Receivable","Building","Patent","Goodwill"]', 'Accounts Receivable', 5, 2),
(a_accounting_basic, 'Double-entry bookkeeping means:', 'multiple_choice', '["Every transaction affects at least two accounts","Recording transactions twice","Having two accountants","Using two ledgers"]', 'Every transaction affects at least two accounts', 5, 3),
(a_accounting_basic, 'GAAP stands for:', 'multiple_choice', '["Generally Accepted Accounting Principles","Global Accounting Assessment Program","General Audit and Analysis Procedures","Government Approved Accounting Practices"]', 'Generally Accepted Accounting Principles', 5, 4),
(a_accounting_basic, 'A debit increases which type of account?', 'multiple_choice', '["Assets","Liabilities","Revenue","Equity"]', 'Assets', 5, 5),
(a_accounting_basic, 'Accrual accounting records revenue when:', 'multiple_choice', '["It is earned, regardless of cash receipt","Cash is received","Invoice is sent","Contract is signed"]', 'It is earned, regardless of cash receipt', 5, 6),
(a_accounting_basic, 'What is a trial balance?', 'multiple_choice', '["A list of all ledger balances to verify debits equal credits","A court document","A test report","A balance sheet draft"]', 'A list of all ledger balances to verify debits equal credits', 5, 7),
(a_accounting_basic, 'Accounts payable is classified as:', 'multiple_choice', '["Current liability","Current asset","Revenue","Expense"]', 'Current liability', 5, 8),
(a_accounting_basic, 'The matching principle states:', 'multiple_choice', '["Expenses should be matched with related revenues in the same period","All expenses are equal","Revenues match liabilities","Assets match equity"]', 'Expenses should be matched with related revenues in the same period', 5, 9),
(a_accounting_basic, 'What is a journal entry?', 'multiple_choice', '["A record of a financial transaction in chronological order","A diary entry","A bank statement","A tax form"]', 'A record of a financial transaction in chronological order', 5, 10),
(a_accounting_basic, 'Retained earnings represent:', 'multiple_choice', '["Cumulative profits not distributed as dividends","Cash in the bank","Total revenue","Employee benefits"]', 'Cumulative profits not distributed as dividends', 5, 11),
(a_accounting_basic, 'An audit is:', 'multiple_choice', '["An examination of financial records for accuracy","A type of tax","A bank loan","A financial transaction"]', 'An examination of financial records for accuracy', 5, 12),
(a_accounting_basic, 'Cost of goods sold includes:', 'multiple_choice', '["Direct costs of producing goods sold","Marketing expenses","Administrative salaries","Rent"]', 'Direct costs of producing goods sold', 5, 13),
(a_accounting_basic, 'What is a general ledger?', 'multiple_choice', '["The main accounting record containing all accounts","A specific customer account","A bank statement","A tax return"]', 'The main accounting record containing all accounts', 5, 14),
(a_accounting_basic, 'Gross profit is calculated as:', 'multiple_choice', '["Revenue - Cost of Goods Sold","Revenue - All Expenses","Assets - Liabilities","Cash In - Cash Out"]', 'Revenue - Cost of Goods Sold', 5, 15),
(a_accounting_basic, 'What is a fiscal year?', 'multiple_choice', '["A 12-month period used for financial reporting","A calendar year only","A tax deadline","A budget cycle"]', 'A 12-month period used for financial reporting', 5, 16),
(a_accounting_basic, 'Prepaid expenses are classified as:', 'multiple_choice', '["Assets","Liabilities","Revenue","Equity"]', 'Assets', 5, 17),
(a_accounting_basic, 'What is an income statement?', 'multiple_choice', '["A report showing revenues and expenses over a period","A list of assets","A bank balance","A tax form"]', 'A report showing revenues and expenses over a period', 5, 18),
(a_accounting_basic, 'The going concern principle assumes:', 'multiple_choice', '["A business will continue to operate indefinitely","The business is closing","Only short-term planning","Cash basis accounting"]', 'A business will continue to operate indefinitely', 5, 19),
(a_accounting_basic, 'What is bank reconciliation?', 'multiple_choice', '["Comparing company records with bank statement to find differences","Opening a bank account","Closing an account","Transferring funds"]', 'Comparing company records with bank statement to find differences', 5, 20),

-- BANKING OPERATIONS (20 questions)
(a_banking_ops, 'KYC stands for:', 'multiple_choice', '["Know Your Customer","Keep Your Cash","Key Yield Calculation","Knowledge Year Certification"]', 'Know Your Customer', 5, 1),
(a_banking_ops, 'Core banking system enables:', 'multiple_choice', '["Real-time transaction processing across branches","Marketing campaigns","Staff management","Building maintenance"]', 'Real-time transaction processing across branches', 5, 2),
(a_banking_ops, 'What is a demand deposit?', 'multiple_choice', '["An account where funds can be withdrawn at any time","A fixed-term deposit","A loan","An investment fund"]', 'An account where funds can be withdrawn at any time', 5, 3),
(a_banking_ops, 'SWIFT is used for:', 'multiple_choice', '["International financial messaging between banks","Domestic transfers only","ATM operations","Credit scoring"]', 'International financial messaging between banks', 5, 4),
(a_banking_ops, 'What is credit underwriting?', 'multiple_choice', '["Assessing a borrower''s creditworthiness and risk","Writing checks","Opening accounts","Processing deposits"]', 'Assessing a borrower''s creditworthiness and risk', 5, 5),
(a_banking_ops, 'NPA stands for:', 'multiple_choice', '["Non-Performing Asset","New Processing Agreement","Net Profit Amount","National Payment Authority"]', 'Non-Performing Asset', 5, 6),
(a_banking_ops, 'What is a letter of credit?', 'multiple_choice', '["A guarantee of payment from a bank on behalf of a buyer","A complaint letter","A reference letter","A loan application"]', 'A guarantee of payment from a bank on behalf of a buyer', 5, 7),
(a_banking_ops, 'The Basel framework is primarily about:', 'multiple_choice', '["Bank capital adequacy and risk management","Marketing standards","Customer service","Branch design"]', 'Bank capital adequacy and risk management', 5, 8),
(a_banking_ops, 'What is a clearing house?', 'multiple_choice', '["An intermediary that settles transactions between banks","A storage facility","A bank branch","A trading floor"]', 'An intermediary that settles transactions between banks', 5, 9),
(a_banking_ops, 'Repo rate is:', 'multiple_choice', '["Rate at which central bank lends to commercial banks","Interest on savings","ATM withdrawal fee","Currency exchange rate"]', 'Rate at which central bank lends to commercial banks', 5, 10),
(a_banking_ops, 'What is trade finance?', 'multiple_choice', '["Financial instruments and products used in international trade","Stock trading","Day trading","Forex speculation"]', 'Financial instruments and products used in international trade', 5, 11),
(a_banking_ops, 'CRR stands for:', 'multiple_choice', '["Cash Reserve Ratio","Credit Risk Rating","Customer Retention Rate","Capital Return Rate"]', 'Cash Reserve Ratio', 5, 12),
(a_banking_ops, 'What is a nostro account?', 'multiple_choice', '["An account held by a domestic bank in a foreign bank","A personal savings account","A loan account","A credit card account"]', 'An account held by a domestic bank in a foreign bank', 5, 13),
(a_banking_ops, 'What does AML stand for?', 'multiple_choice', '["Anti-Money Laundering","Asset Management License","Automated Marketing Logic","Account Management Level"]', 'Anti-Money Laundering', 5, 14),
(a_banking_ops, 'Collateral in banking refers to:', 'multiple_choice', '["Asset pledged as security for a loan","Interest earned","Monthly payment","Service fee"]', 'Asset pledged as security for a loan', 5, 15),
(a_banking_ops, 'What is digital banking?', 'multiple_choice', '["Banking services delivered via digital channels","Only ATM banking","Phone banking only","In-branch services"]', 'Banking services delivered via digital channels', 5, 16),
(a_banking_ops, 'Treasury management involves:', 'multiple_choice', '["Managing a bank''s liquidity, investments, and risk","Customer service","Branch operations","Marketing"]', 'Managing a bank''s liquidity, investments, and risk', 5, 17),
(a_banking_ops, 'What is a fixed deposit?', 'multiple_choice', '["A deposit held for a fixed term at a set interest rate","An on-demand account","A checking account","A credit facility"]', 'A deposit held for a fixed term at a set interest rate', 5, 18),
(a_banking_ops, 'Mortgage is a type of:', 'multiple_choice', '["Secured loan for property purchase","Unsecured loan","Savings product","Insurance"]', 'Secured loan for property purchase', 5, 19),
(a_banking_ops, 'What is financial inclusion?', 'multiple_choice', '["Making financial services accessible to all segments of society","Excluding risky customers","Premium banking","Corporate banking only"]', 'Making financial services accessible to all segments of society', 5, 20),

-- DATA ANALYST ASSESSMENT (20 questions)
(a_data_analyst, 'SQL JOIN combines data from:', 'multiple_choice', '["Two or more related tables","One table only","Files on disk","Web APIs"]', 'Two or more related tables', 5, 1),
(a_data_analyst, 'What is a histogram?', 'multiple_choice', '["A chart showing frequency distribution of data","A pie chart","A scatter plot","A line graph"]', 'A chart showing frequency distribution of data', 5, 2),
(a_data_analyst, 'The mean of 2, 4, 6, 8, 10 is:', 'multiple_choice', '["6","5","7","8"]', '6', 5, 3),
(a_data_analyst, 'What is a primary key in a database?', 'multiple_choice', '["A unique identifier for each record","Any column","The first column","A password"]', 'A unique identifier for each record', 5, 4),
(a_data_analyst, 'Standard deviation measures:', 'multiple_choice', '["Spread of data around the mean","Average value","Maximum value","Minimum value"]', 'Spread of data around the mean', 5, 5),
(a_data_analyst, 'What does ETL stand for?', 'multiple_choice', '["Extract, Transform, Load","Enter, Test, Launch","Edit, Transfer, Link","Evaluate, Track, Log"]', 'Extract, Transform, Load', 5, 6),
(a_data_analyst, 'A scatter plot shows:', 'multiple_choice', '["Relationship between two variables","Frequency distribution","Time series only","Categorical data only"]', 'Relationship between two variables', 5, 7),
(a_data_analyst, 'What is a null hypothesis?', 'multiple_choice', '["Statement that there is no significant effect or relationship","Always true statement","A proven theory","A data error"]', 'Statement that there is no significant effect or relationship', 5, 8),
(a_data_analyst, 'GROUP BY in SQL is used to:', 'multiple_choice', '["Aggregate data based on one or more columns","Sort data","Delete data","Insert data"]', 'Aggregate data based on one or more columns', 5, 9),
(a_data_analyst, 'What is a KPI?', 'multiple_choice', '["Key Performance Indicator","Key Process Input","Knowledge Platform Index","Kernel Processing Interface"]', 'Key Performance Indicator', 5, 10),
(a_data_analyst, 'Correlation coefficient of 0 means:', 'multiple_choice', '["No linear relationship","Perfect positive correlation","Perfect negative correlation","Data error"]', 'No linear relationship', 5, 11),
(a_data_analyst, 'A dashboard is:', 'multiple_choice', '["Visual display of key metrics and data","A database table","A code editor","A server"]', 'Visual display of key metrics and data', 5, 12),
(a_data_analyst, 'What is data normalization?', 'multiple_choice', '["Organizing data to reduce redundancy","Deleting duplicate data","Encrypting data","Compressing files"]', 'Organizing data to reduce redundancy', 5, 13),
(a_data_analyst, 'Which SQL clause filters grouped results?', 'multiple_choice', '["HAVING","WHERE","ORDER BY","GROUP BY"]', 'HAVING', 5, 14),
(a_data_analyst, 'A/B testing is used to:', 'multiple_choice', '["Compare two versions to see which performs better","Test application bugs","Audit data quality","Backup databases"]', 'Compare two versions to see which performs better', 5, 15),
(a_data_analyst, 'What is a data warehouse?', 'multiple_choice', '["Central repository for integrated data from multiple sources","A single database table","A file server","An API endpoint"]', 'Central repository for integrated data from multiple sources', 5, 16),
(a_data_analyst, 'The median is:', 'multiple_choice', '["Middle value when data is sorted","Average value","Most frequent value","Range of values"]', 'Middle value when data is sorted', 5, 17),
(a_data_analyst, 'Power BI and Tableau are:', 'multiple_choice', '["Data visualization tools","Programming languages","Databases","Operating systems"]', 'Data visualization tools', 5, 18),
(a_data_analyst, 'What is regression analysis?', 'multiple_choice', '["Statistical method to model relationship between variables","Deleting old data","Compressing files","Sorting records"]', 'Statistical method to model relationship between variables', 5, 19),
(a_data_analyst, 'What is data cleaning?', 'multiple_choice', '["Identifying and correcting errors in datasets","Deleting all data","Moving data between systems","Encrypting data"]', 'Identifying and correcting errors in datasets', 5, 20),

-- PHARMACY TECHNICIAN ESSENTIALS (20 questions)
(a_pharmacy_tech, 'What does OTC stand for?', 'multiple_choice', '["Over The Counter","On Time Care","Organic Treatment Compound","Official Treatment Code"]', 'Over The Counter', 5, 1),
(a_pharmacy_tech, 'A prescription is issued by:', 'multiple_choice', '["A licensed healthcare provider","Any pharmacy employee","The patient","An insurance company"]', 'A licensed healthcare provider', 5, 2),
(a_pharmacy_tech, 'What is a generic drug?', 'multiple_choice', '["A drug with the same active ingredient as a brand-name drug","A new experimental drug","A natural remedy","A vitamin supplement"]', 'A drug with the same active ingredient as a brand-name drug', 5, 3),
(a_pharmacy_tech, 'Controlled substances are classified into:', 'multiple_choice', '["Schedules I through V","Categories A through E","Levels 1 through 10","Tiers 1 through 3"]', 'Schedules I through V', 5, 4),
(a_pharmacy_tech, 'What does NDC stand for?', 'multiple_choice', '["National Drug Code","New Drug Certification","Non-Dispensing Category","National Dosage Calculator"]', 'National Drug Code', 5, 5),
(a_pharmacy_tech, 'The ''sig'' on a prescription refers to:', 'multiple_choice', '["Directions for the patient","Drug name","Prescriber signature","Insurance code"]', 'Directions for the patient', 5, 6),
(a_pharmacy_tech, 'What is compounding?', 'multiple_choice', '["Preparing a customized medication for a patient","Counting pills","Stocking shelves","Processing insurance"]', 'Preparing a customized medication for a patient', 5, 7),
(a_pharmacy_tech, 'HIPAA in pharmacy protects:', 'multiple_choice', '["Patient health information","Drug prices","Pharmacy profits","Employee records"]', 'Patient health information', 5, 8),
(a_pharmacy_tech, 'What is a drug interaction?', 'multiple_choice', '["When one drug affects the activity of another","A drug allergy","A side effect","A dosage error"]', 'When one drug affects the activity of another', 5, 9),
(a_pharmacy_tech, 'An adverse drug reaction (ADR) is:', 'multiple_choice', '["An unintended harmful reaction to a drug at normal doses","An allergic reaction only","A dosage error","Drug expiration"]', 'An unintended harmful reaction to a drug at normal doses', 5, 10),
(a_pharmacy_tech, 'Pharmacy inventory management includes:', 'multiple_choice', '["Stock rotation, reordering, and expiration tracking","Only counting pills","Just placing orders","Filing prescriptions"]', 'Stock rotation, reordering, and expiration tracking', 5, 11),
(a_pharmacy_tech, 'What is a formulary?', 'multiple_choice', '["A list of medications approved for use by an insurance plan","A drug formula","A prescription pad","A pharmacy license"]', 'A list of medications approved for use by an insurance plan', 5, 12),
(a_pharmacy_tech, 'The route of administration ''PO'' means:', 'multiple_choice', '["By mouth (oral)","Intravenous","Topical","Intramuscular"]', 'By mouth (oral)', 5, 13),
(a_pharmacy_tech, 'What is a unit dose?', 'multiple_choice', '["A single dose of medication individually packaged","A bulk container","A prescription refill","A drug sample"]', 'A single dose of medication individually packaged', 5, 14),
(a_pharmacy_tech, 'DEA number is required for:', 'multiple_choice', '["Prescribing controlled substances","All medications","OTC drugs","Vitamins"]', 'Prescribing controlled substances', 5, 15),
(a_pharmacy_tech, 'What does ''prn'' mean on a prescription?', 'multiple_choice', '["As needed","Before meals","After meals","At bedtime"]', 'As needed', 5, 16),
(a_pharmacy_tech, 'Cold chain management is important for:', 'multiple_choice', '["Temperature-sensitive medications like vaccines","All medications","Only tablets","Only liquids"]', 'Temperature-sensitive medications like vaccines', 5, 17),
(a_pharmacy_tech, 'What is medication reconciliation?', 'multiple_choice', '["Comparing patient medications across care settings","Counting inventory","Filing prescriptions","Processing returns"]', 'Comparing patient medications across care settings', 5, 18),
(a_pharmacy_tech, 'A DAW code indicates:', 'multiple_choice', '["Dispense As Written - brand name must be used","Drug Already Withdrawn","Dosage Adjusted Weekly","Direct Administration Warning"]', 'Dispense As Written - brand name must be used', 5, 19),
(a_pharmacy_tech, 'What is a look-alike/sound-alike (LASA) error?', 'multiple_choice', '["Dispensing wrong medication due to similar names or appearance","A billing error","An insurance issue","A scheduling mistake"]', 'Dispensing wrong medication due to similar names or appearance', 5, 20),

-- SALES FUNDAMENTALS (20 questions)
(a_sales_gen, 'What is a sales funnel?', 'multiple_choice', '["A model representing the customer journey from awareness to purchase","A type of report","A marketing budget","A pricing strategy"]', 'A model representing the customer journey from awareness to purchase', 5, 1),
(a_sales_gen, 'CRM stands for:', 'multiple_choice', '["Customer Relationship Management","Cash Revenue Model","Corporate Risk Management","Client Retention Metric"]', 'Customer Relationship Management', 5, 2),
(a_sales_gen, 'What is a sales quota?', 'multiple_choice', '["A target revenue or unit amount for a salesperson","A customer discount","A marketing budget","An expense limit"]', 'A target revenue or unit amount for a salesperson', 5, 3),
(a_sales_gen, 'Cold calling is:', 'multiple_choice', '["Contacting potential customers who have not expressed interest","Calling existing customers","Calling the helpdesk","Making internal calls"]', 'Contacting potential customers who have not expressed interest', 5, 4),
(a_sales_gen, 'What is upselling?', 'multiple_choice', '["Encouraging purchase of a higher-end or upgraded product","Selling at a discount","Returning products","Closing the store"]', 'Encouraging purchase of a higher-end or upgraded product', 5, 5),
(a_sales_gen, 'Sales pipeline refers to:', 'multiple_choice', '["All deals in progress at various stages","A water pipe in the office","A data pipeline","A manufacturing process"]', 'All deals in progress at various stages', 5, 6),
(a_sales_gen, 'What is lead qualification?', 'multiple_choice', '["Determining if a prospect is likely to become a customer","Generating leads","Closing deals","Sending invoices"]', 'Determining if a prospect is likely to become a customer', 5, 7),
(a_sales_gen, 'BANT stands for:', 'multiple_choice', '["Budget, Authority, Need, Timeline","Buy, Ask, Negotiate, Transfer","Best, Average, Normal, Top","Begin, Analyze, Negotiate, Terminate"]', 'Budget, Authority, Need, Timeline', 5, 8),
(a_sales_gen, 'What is cross-selling?', 'multiple_choice', '["Selling complementary products to existing customers","Selling competitors'' products","International sales","Returns processing"]', 'Selling complementary products to existing customers', 5, 9),
(a_sales_gen, 'A sales objection is:', 'multiple_choice', '["A concern raised by a prospect during the sales process","A formal complaint","A legal issue","A pricing error"]', 'A concern raised by a prospect during the sales process', 5, 10),
(a_sales_gen, 'What is consultative selling?', 'multiple_choice', '["Understanding customer needs before recommending solutions","Hard selling techniques","Discounting heavily","Cold calling only"]', 'Understanding customer needs before recommending solutions', 5, 11),
(a_sales_gen, 'What is customer lifetime value (CLV)?', 'multiple_choice', '["Total revenue expected from a customer over the relationship","One-time purchase value","Monthly revenue","Annual revenue"]', 'Total revenue expected from a customer over the relationship', 5, 12),
(a_sales_gen, 'Sales enablement includes:', 'multiple_choice', '["Tools, content, and training to help sales teams sell more effectively","Only discounts","Only cold calls","Only presentations"]', 'Tools, content, and training to help sales teams sell more effectively', 5, 13),
(a_sales_gen, 'What is a value proposition?', 'multiple_choice', '["A statement explaining how a product solves a problem or adds value","A price offer","A discount code","A warranty"]', 'A statement explaining how a product solves a problem or adds value', 5, 14),
(a_sales_gen, 'What does MQL stand for?', 'multiple_choice', '["Marketing Qualified Lead","Maximum Quality Level","Monthly Quota Limit","Minimum Qualification Level"]', 'Marketing Qualified Lead', 5, 15),
(a_sales_gen, 'Social selling is:', 'multiple_choice', '["Using social media to identify and engage with prospects","Selling at events only","Door-to-door selling","Telemarketing"]', 'Using social media to identify and engage with prospects', 5, 16),
(a_sales_gen, 'What is churn rate?', 'multiple_choice', '["Percentage of customers who stop using a product over time","Revenue growth rate","Employee turnover","Marketing spend"]', 'Percentage of customers who stop using a product over time', 5, 17),
(a_sales_gen, 'A demo in sales is:', 'multiple_choice', '["A product demonstration to a potential buyer","A demolition","A prototype","A test environment"]', 'A product demonstration to a potential buyer', 5, 18),
(a_sales_gen, 'What is territory management?', 'multiple_choice', '["Organizing and managing sales reps across geographic or account segments","Managing office space","Real estate","Facility management"]', 'Organizing and managing sales reps across geographic or account segments', 5, 19),
(a_sales_gen, 'Closing a deal means:', 'multiple_choice', '["Getting the customer to agree to purchase","Shutting down the business","Ending a meeting","Filing paperwork"]', 'Getting the customer to agree to purchase', 5, 20),

-- CUSTOMER SUPPORT EXCELLENCE (20 questions)
(a_cs_support, 'SLA stands for:', 'multiple_choice', '["Service Level Agreement","Sales Lead Analysis","System Log Audit","Support Level Assessment"]', 'Service Level Agreement', 5, 1),
(a_cs_support, 'First Contact Resolution (FCR) measures:', 'multiple_choice', '["Percentage of issues resolved on first interaction","Speed of first response","Number of contacts per day","Customer satisfaction only"]', 'Percentage of issues resolved on first interaction', 5, 2),
(a_cs_support, 'Active listening involves:', 'multiple_choice', '["Fully concentrating, understanding, and responding to the customer","Just hearing the customer","Taking notes only","Waiting to speak"]', 'Fully concentrating, understanding, and responding to the customer', 5, 3),
(a_cs_support, 'What is a knowledge base?', 'multiple_choice', '["A repository of information for self-service support","A database of customers","An email inbox","A chatbot"]', 'A repository of information for self-service support', 5, 4),
(a_cs_support, 'CSAT measures:', 'multiple_choice', '["Customer Satisfaction","Cost Structure Analysis","Customer Service Availability","Contact System Automation"]', 'Customer Satisfaction', 5, 5),
(a_cs_support, 'Escalation in support means:', 'multiple_choice', '["Transferring an issue to a higher-level team","Closing a ticket","Ignoring the issue","Sending an email"]', 'Transferring an issue to a higher-level team', 5, 6),
(a_cs_support, 'What is NPS?', 'multiple_choice', '["Net Promoter Score","New Payment System","National Product Standard","Network Processing Speed"]', 'Net Promoter Score', 5, 7),
(a_cs_support, 'A ticketing system is used to:', 'multiple_choice', '["Track, manage, and resolve customer issues","Sell tickets","Book appointments","Send marketing emails"]', 'Track, manage, and resolve customer issues', 5, 8),
(a_cs_support, 'Empathy in customer service means:', 'multiple_choice', '["Understanding and sharing the customer''s feelings","Agreeing with everything","Offering discounts","Being sympathetic only"]', 'Understanding and sharing the customer''s feelings', 5, 9),
(a_cs_support, 'What is omnichannel support?', 'multiple_choice', '["Providing consistent support across multiple channels","Supporting one channel only","Phone support only","Email support only"]', 'Providing consistent support across multiple channels', 5, 10),
(a_cs_support, 'Average Handle Time (AHT) is:', 'multiple_choice', '["Average duration of a customer interaction","Number of calls per day","Wait time only","Hold time only"]', 'Average duration of a customer interaction', 5, 11),
(a_cs_support, 'De-escalation techniques include:', 'multiple_choice', '["Remaining calm, acknowledging feelings, offering solutions","Arguing back","Hanging up","Ignoring the customer"]', 'Remaining calm, acknowledging feelings, offering solutions', 5, 12),
(a_cs_support, 'What is a canned response?', 'multiple_choice', '["A pre-written template for common questions","Canned food reference","An automated call","A recorded message"]', 'A pre-written template for common questions', 5, 13),
(a_cs_support, 'Customer churn prevention strategies include:', 'multiple_choice', '["Proactive outreach, loyalty programs, and feedback loops","Ignoring complaints","Raising prices","Reducing support hours"]', 'Proactive outreach, loyalty programs, and feedback loops', 5, 14),
(a_cs_support, 'What is a service recovery?', 'multiple_choice', '["Turning a negative customer experience into a positive one","Recovering lost data","System backup","Restarting services"]', 'Turning a negative customer experience into a positive one', 5, 15),
(a_cs_support, 'CES stands for:', 'multiple_choice', '["Customer Effort Score","Customer Email System","Central Engagement Service","Communication Enhancement Software"]', 'Customer Effort Score', 5, 16),
(a_cs_support, 'What is a chatbot?', 'multiple_choice', '["An AI-powered tool that simulates human conversation","A chat room","A messaging app","A social media platform"]', 'An AI-powered tool that simulates human conversation', 5, 17),
(a_cs_support, 'Quality assurance in support involves:', 'multiple_choice', '["Monitoring and evaluating agent performance and interactions","Only counting tickets","Just tracking time","Reviewing code"]', 'Monitoring and evaluating agent performance and interactions', 5, 18),
(a_cs_support, 'What is customer onboarding?', 'multiple_choice', '["Guiding new customers to successfully use a product","Firing customers","Marketing campaigns","Sales calls"]', 'Guiding new customers to successfully use a product', 5, 19),
(a_cs_support, 'A warm transfer means:', 'multiple_choice', '["Introducing the customer to the next agent with context","Disconnecting the call","Putting on hold indefinitely","Sending an email instead"]', 'Introducing the customer to the next agent with context', 5, 20);

-- Insert remaining assessments' questions (abbreviated for the less common domains)

-- INVESTMENT ANALYSIS (20 questions)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, points, order_index) VALUES
(a_finance_invest, 'The efficient market hypothesis states:', 'multiple_choice', '["Stock prices reflect all available information","Markets are always inefficient","Only insiders know true value","Prices are random"]', 'Stock prices reflect all available information', 5, 1),
(a_finance_invest, 'What is a mutual fund?', 'multiple_choice', '["A pooled investment vehicle managed by professionals","A bank account","A single stock","A bond"]', 'A pooled investment vehicle managed by professionals', 5, 2),
(a_finance_invest, 'Dividend yield is calculated as:', 'multiple_choice', '["Annual dividend / Stock price","Stock price / Earnings","Revenue / Shares","Profit / Assets"]', 'Annual dividend / Stock price', 5, 3),
(a_finance_invest, 'What is an ETF?', 'multiple_choice', '["Exchange-Traded Fund","Electronic Transfer Fee","Equity Trading Framework","External Tax Form"]', 'Exchange-Traded Fund', 5, 4),
(a_finance_invest, 'Market capitalization equals:', 'multiple_choice', '["Share price × Total shares outstanding","Revenue × Profit margin","Assets - Liabilities","Debt / Equity"]', 'Share price × Total shares outstanding', 5, 5),
(a_finance_invest, 'What is a bear market?', 'multiple_choice', '["A market decline of 20% or more","A rising market","A stable market","A new market"]', 'A market decline of 20% or more', 5, 6),
(a_finance_invest, 'Asset allocation refers to:', 'multiple_choice', '["Distributing investments across different asset classes","Buying one stock","Selling all assets","Trading daily"]', 'Distributing investments across different asset classes', 5, 7),
(a_finance_invest, 'What is the yield curve?', 'multiple_choice', '["Graph showing interest rates across different bond maturities","Stock price chart","Revenue growth chart","Profit margin chart"]', 'Graph showing interest rates across different bond maturities', 5, 8),
(a_finance_invest, 'IRR stands for:', 'multiple_choice', '["Internal Rate of Return","Interest Rate Ratio","Investment Revenue Result","Indexed Return Rate"]', 'Internal Rate of Return', 5, 9),
(a_finance_invest, 'What is dollar-cost averaging?', 'multiple_choice', '["Investing a fixed amount at regular intervals regardless of price","Timing the market","Buying at the lowest price","Selling at the highest price"]', 'Investing a fixed amount at regular intervals regardless of price', 5, 10),
(a_finance_invest, 'Blue-chip stocks are:', 'multiple_choice', '["Shares of large, well-established companies","Penny stocks","New IPOs","Cryptocurrency"]', 'Shares of large, well-established companies', 5, 11),
(a_finance_invest, 'What is a bond coupon?', 'multiple_choice', '["Periodic interest payment on a bond","A discount code","A trading fee","A tax deduction"]', 'Periodic interest payment on a bond', 5, 12),
(a_finance_invest, 'Short selling involves:', 'multiple_choice', '["Selling borrowed shares hoping to buy back at a lower price","Buying shares for the long term","Day trading","Options trading"]', 'Selling borrowed shares hoping to buy back at a lower price', 5, 13),
(a_finance_invest, 'What is a REIT?', 'multiple_choice', '["Real Estate Investment Trust","Retirement Economic Income Tax","Revenue Enhancement Investment Tool","Risk Evaluation Index Tool"]', 'Real Estate Investment Trust', 5, 14),
(a_finance_invest, 'Alpha in investing measures:', 'multiple_choice', '["Excess return relative to a benchmark","Total return","Market risk","Dividend yield"]', 'Excess return relative to a benchmark', 5, 15),
(a_finance_invest, 'What is a prospectus?', 'multiple_choice', '["A formal document describing an investment offering","A business plan","A marketing brochure","A financial statement"]', 'A formal document describing an investment offering', 5, 16),
(a_finance_invest, 'Fundamental analysis evaluates:', 'multiple_choice', '["A company''s financial health and intrinsic value","Only chart patterns","Market sentiment only","Trading volume only"]', 'A company''s financial health and intrinsic value', 5, 17),
(a_finance_invest, 'What is portfolio rebalancing?', 'multiple_choice', '["Adjusting asset allocation back to target proportions","Selling everything","Buying more of one stock","Closing an account"]', 'Adjusting asset allocation back to target proportions', 5, 18),
(a_finance_invest, 'An IPO is:', 'multiple_choice', '["Initial Public Offering - first sale of stock to the public","Internal Profit Operation","Investment Portfolio Option","Indexed Price Order"]', 'Initial Public Offering - first sale of stock to the public', 5, 19),
(a_finance_invest, 'What is a hedge fund?', 'multiple_choice', '["An alternative investment fund using diverse strategies for high returns","A bank account","A pension fund","A savings plan"]', 'An alternative investment fund using diverse strategies for high returns', 5, 20);

-- CLINICAL OPERATIONS (20 questions)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, points, order_index) VALUES
(a_healthcare_admin, 'Clinical decision support systems help:', 'multiple_choice', '["Improve clinical decision-making with evidence-based recommendations","Manage billing only","Schedule staff","Track inventory"]', 'Improve clinical decision-making with evidence-based recommendations', 5, 1),
(a_healthcare_admin, 'What is a clinical trial phase I?', 'multiple_choice', '["Testing safety and dosage in a small group","Large-scale effectiveness testing","Post-market surveillance","Animal testing"]', 'Testing safety and dosage in a small group', 5, 2),
(a_healthcare_admin, 'Root cause analysis in healthcare:', 'multiple_choice', '["Identifies underlying causes of adverse events","Analyzes financial data","Reviews marketing strategies","Assesses facility design"]', 'Identifies underlying causes of adverse events', 5, 3),
(a_healthcare_admin, 'What is an EHR interoperability?', 'multiple_choice', '["Ability of different EHR systems to exchange and use data","A type of medical device","A billing system","A patient portal"]', 'Ability of different EHR systems to exchange and use data', 5, 4),
(a_healthcare_admin, 'PDSA cycle stands for:', 'multiple_choice', '["Plan-Do-Study-Act","Process-Design-System-Analysis","Patient-Doctor-Schedule-Appointment","Program-Development-Service-Audit"]', 'Plan-Do-Study-Act', 5, 5),
(a_healthcare_admin, 'What is antimicrobial stewardship?', 'multiple_choice', '["Coordinated interventions to optimize antibiotic use","A cleaning protocol","A staffing model","A billing procedure"]', 'Coordinated interventions to optimize antibiotic use', 5, 6),
(a_healthcare_admin, 'Lean methodology in healthcare aims to:', 'multiple_choice', '["Eliminate waste and improve efficiency","Increase spending","Add more steps","Reduce staff"]', 'Eliminate waste and improve efficiency', 5, 7),
(a_healthcare_admin, 'What is patient acuity?', 'multiple_choice', '["Severity of a patient''s condition and care needs","Patient satisfaction score","Length of stay","Insurance type"]', 'Severity of a patient''s condition and care needs', 5, 8),
(a_healthcare_admin, 'OSHA in healthcare protects:', 'multiple_choice', '["Worker safety and health","Patient privacy","Medical records","Drug supplies"]', 'Worker safety and health', 5, 9),
(a_healthcare_admin, 'What is a medication error?', 'multiple_choice', '["Any preventable event that may cause inappropriate medication use","A billing mistake","A scheduling conflict","A supply shortage"]', 'Any preventable event that may cause inappropriate medication use', 5, 10),
(a_healthcare_admin, 'Clinical governance includes:', 'multiple_choice', '["Systems for maintaining and improving quality of care","Only financial management","Just staffing","Equipment maintenance only"]', 'Systems for maintaining and improving quality of care', 5, 11),
(a_healthcare_admin, 'What is discharge planning?', 'multiple_choice', '["Preparing patients for leaving the hospital safely","Firing employees","Closing a department","Ending a shift"]', 'Preparing patients for leaving the hospital safely', 5, 12),
(a_healthcare_admin, 'EMTALA requires:', 'multiple_choice', '["Emergency treatment regardless of ability to pay","Insurance verification before treatment","Cash payment upfront","Referral to another facility"]', 'Emergency treatment regardless of ability to pay', 5, 13),
(a_healthcare_admin, 'What is a CLABSI?', 'multiple_choice', '["Central Line-Associated Bloodstream Infection","A billing code","A patient satisfaction metric","A scheduling system"]', 'Central Line-Associated Bloodstream Infection', 5, 14),
(a_healthcare_admin, 'Nurse-to-patient ratios affect:', 'multiple_choice', '["Patient safety and care quality","Only costs","Only scheduling","Only recruitment"]', 'Patient safety and care quality', 5, 15),
(a_healthcare_admin, 'What is a rapid response team?', 'multiple_choice', '["A team that responds to deteriorating patients on non-ICU units","An IT support team","A maintenance crew","A marketing team"]', 'A team that responds to deteriorating patients on non-ICU units', 5, 16),
(a_healthcare_admin, 'What does HL7 stand for?', 'multiple_choice', '["Health Level Seven - a standard for health data exchange","Hospital Level 7","Healthcare License 7","Health Lab 7"]', 'Health Level Seven - a standard for health data exchange', 5, 17),
(a_healthcare_admin, 'What is a patient safety event?', 'multiple_choice', '["Any event that could have or did result in harm to a patient","A scheduled appointment","A routine checkup","A billing event"]', 'Any event that could have or did result in harm to a patient', 5, 18),
(a_healthcare_admin, 'Credentialing in healthcare involves:', 'multiple_choice', '["Verifying qualifications and competency of healthcare providers","Processing insurance claims","Managing inventory","Scheduling appointments"]', 'Verifying qualifications and competency of healthcare providers', 5, 19),
(a_healthcare_admin, 'What is a clinical dashboard?', 'multiple_choice', '["Visual display of key clinical metrics for monitoring performance","A patient bed","A medical device","A pharmacy counter"]', 'Visual display of key clinical metrics for monitoring performance', 5, 20);

-- PHARMACY MANAGEMENT (20 questions)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, points, order_index) VALUES
(a_pharmacy_mgmt, 'Good Pharmacy Practice (GPP) ensures:', 'multiple_choice', '["Quality pharmaceutical care and patient safety","Maximum profit","Faster dispensing","Fewer staff"]', 'Quality pharmaceutical care and patient safety', 5, 1),
(a_pharmacy_mgmt, 'Medication Therapy Management (MTM) involves:', 'multiple_choice', '["Comprehensive review of all medications with the patient","Just counting pills","Only dispensing","Stock management"]', 'Comprehensive review of all medications with the patient', 5, 2),
(a_pharmacy_mgmt, 'A pharmacy benefit manager (PBM) role is:', 'multiple_choice', '["Managing prescription drug programs for insurers","Operating a pharmacy","Manufacturing drugs","Training pharmacists"]', 'Managing prescription drug programs for insurers', 5, 3),
(a_pharmacy_mgmt, 'USP 800 addresses:', 'multiple_choice', '["Handling of hazardous drugs","General compounding","Dietary supplements","Over-the-counter medications"]', 'Handling of hazardous drugs', 5, 4),
(a_pharmacy_mgmt, 'What is a prior authorization?', 'multiple_choice', '["Approval from insurance before dispensing certain medications","Patient consent","Doctor''s signature","Lab result"]', 'Approval from insurance before dispensing certain medications', 5, 5),
(a_pharmacy_mgmt, 'Pharmacovigilance is:', 'multiple_choice', '["Monitoring and evaluating drug safety after market release","Drug manufacturing","Drug advertising","Drug pricing"]', 'Monitoring and evaluating drug safety after market release', 5, 6),
(a_pharmacy_mgmt, 'What is a drug recall?', 'multiple_choice', '["Removal of a drug from the market due to safety concerns","A drug discount","A new drug launch","A prescription refill"]', 'Removal of a drug from the market due to safety concerns', 5, 7),
(a_pharmacy_mgmt, 'Clinical pharmacy focuses on:', 'multiple_choice', '["Optimizing medication therapy outcomes for patients","Only dispensing medications","Managing pharmacy finances","Marketing drugs"]', 'Optimizing medication therapy outcomes for patients', 5, 8),
(a_pharmacy_mgmt, 'What is a 340B program?', 'multiple_choice', '["Federal program providing discounted drugs to eligible healthcare organizations","A training program","An insurance plan","A pharmacy chain"]', 'Federal program providing discounted drugs to eligible healthcare organizations', 5, 9),
(a_pharmacy_mgmt, 'Pharmacy compliance includes:', 'multiple_choice', '["Following all regulatory and legal requirements","Just filling prescriptions","Only inventory management","Staff scheduling"]', 'Following all regulatory and legal requirements', 5, 10),
(a_pharmacy_mgmt, 'What is a medication guide?', 'multiple_choice', '["FDA-approved information for patients about drug risks","A prescription label","A drug advertisement","A training manual"]', 'FDA-approved information for patients about drug risks', 5, 11),
(a_pharmacy_mgmt, 'What is antimicrobial resistance?', 'multiple_choice', '["When bacteria evolve to resist the effects of antibiotics","Drug allergy","Drug interaction","Drug recall"]', 'When bacteria evolve to resist the effects of antibiotics', 5, 12),
(a_pharmacy_mgmt, 'Point-of-care testing in pharmacy:', 'multiple_choice', '["Performing diagnostic tests at the pharmacy","Only selling medications","Just consulting patients","Processing insurance"]', 'Performing diagnostic tests at the pharmacy', 5, 13),
(a_pharmacy_mgmt, 'What is a REMS program?', 'multiple_choice', '["Risk Evaluation and Mitigation Strategy for certain medications","A reward program","A training course","A marketing campaign"]', 'Risk Evaluation and Mitigation Strategy for certain medications', 5, 14),
(a_pharmacy_mgmt, 'Pharmacy automation includes:', 'multiple_choice', '["Robotic dispensing, barcode scanning, and automated counting","Only manual counting","Paper-based records","Phone orders only"]', 'Robotic dispensing, barcode scanning, and automated counting', 5, 15),
(a_pharmacy_mgmt, 'What is a therapeutic substitution?', 'multiple_choice', '["Dispensing a different drug from the same therapeutic class","Giving a placebo","Refusing to fill a prescription","Doubling the dose"]', 'Dispensing a different drug from the same therapeutic class', 5, 16),
(a_pharmacy_mgmt, 'Specialty pharmacy handles:', 'multiple_choice', '["High-cost, complex medications for chronic conditions","Only OTC products","Basic prescriptions","Vitamins only"]', 'High-cost, complex medications for chronic conditions', 5, 17),
(a_pharmacy_mgmt, 'What is a drug utilization review (DUR)?', 'multiple_choice', '["Evaluation of prescribing patterns and drug use","A financial audit","A marketing review","A staffing assessment"]', 'Evaluation of prescribing patterns and drug use', 5, 18),
(a_pharmacy_mgmt, 'Pharmacy informatics focuses on:', 'multiple_choice', '["Using technology to improve medication use and outcomes","Only data entry","Website design","Social media"]', 'Using technology to improve medication use and outcomes', 5, 19),
(a_pharmacy_mgmt, 'What is collaborative drug therapy management?', 'multiple_choice', '["Pharmacists working with physicians to manage patient medications","Just dispensing","Only counseling","Inventory management"]', 'Pharmacists working with physicians to manage patient medications', 5, 20);

-- ADVANCED ACCOUNTING (20 questions)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, points, order_index) VALUES
(a_accounting_adv, 'IFRS stands for:', 'multiple_choice', '["International Financial Reporting Standards","Internal Finance Review System","International Fiscal Regulation Standards","Integrated Financial Record System"]', 'International Financial Reporting Standards', 5, 1),
(a_accounting_adv, 'Deferred tax liability arises when:', 'multiple_choice', '["Tax expense exceeds tax payable in current period","Tax is paid in advance","No tax is owed","Revenue is deferred"]', 'Tax expense exceeds tax payable in current period', 5, 2),
(a_accounting_adv, 'Goodwill in accounting represents:', 'multiple_choice', '["Excess purchase price over fair value of net assets acquired","Total assets","Cash reserves","Equipment value"]', 'Excess purchase price over fair value of net assets acquired', 5, 3),
(a_accounting_adv, 'Consolidation accounting is required when:', 'multiple_choice', '["A parent controls one or more subsidiaries","Two companies trade with each other","A company goes public","A company pays dividends"]', 'A parent controls one or more subsidiaries', 5, 4),
(a_accounting_adv, 'What is transfer pricing?', 'multiple_choice', '["Pricing of transactions between related entities","Setting retail prices","Discounting products","Exchanging currencies"]', 'Pricing of transactions between related entities', 5, 5),
(a_accounting_adv, 'Revenue recognition under IFRS 15 requires:', 'multiple_choice', '["Identifying performance obligations and recognizing revenue when satisfied","Recording revenue when cash is received","Recognizing all revenue upfront","Deferring all revenue"]', 'Identifying performance obligations and recognizing revenue when satisfied', 5, 6),
(a_accounting_adv, 'What is forensic accounting?', 'multiple_choice', '["Investigating financial fraud and disputes","Standard bookkeeping","Tax preparation","Payroll processing"]', 'Investigating financial fraud and disputes', 5, 7),
(a_accounting_adv, 'An impairment loss occurs when:', 'multiple_choice', '["An asset''s carrying amount exceeds its recoverable amount","An asset increases in value","A debt is paid off","Revenue increases"]', 'An asset''s carrying amount exceeds its recoverable amount', 5, 8),
(a_accounting_adv, 'What is a tax loss carryforward?', 'multiple_choice', '["Using current year losses to offset future taxable income","Paying extra tax now","A penalty","A deduction in the current year"]', 'Using current year losses to offset future taxable income', 5, 9),
(a_accounting_adv, 'Fair value measurement requires:', 'multiple_choice', '["Estimating the price in an orderly transaction between market participants","Using historical cost only","Management''s preferred price","The lowest possible value"]', 'Estimating the price in an orderly transaction between market participants', 5, 10),
(a_accounting_adv, 'What is a contingent liability?', 'multiple_choice', '["A potential obligation dependent on a future uncertain event","A definite debt","An asset","Revenue"]', 'A potential obligation dependent on a future uncertain event', 5, 11),
(a_accounting_adv, 'Segment reporting requires disclosure of:', 'multiple_choice', '["Financial information about different business segments","Only total company results","Employee information","Customer data"]', 'Financial information about different business segments', 5, 12),
(a_accounting_adv, 'What is an operating lease under IFRS 16?', 'multiple_choice', '["IFRS 16 requires most leases to be recognized on balance sheet","A lease not on the balance sheet","A purchase agreement","A rental agreement with no obligations"]', 'IFRS 16 requires most leases to be recognized on balance sheet', 5, 13),
(a_accounting_adv, 'Earnings per share (EPS) is calculated as:', 'multiple_choice', '["Net income / Weighted average shares outstanding","Revenue / Total shares","Assets / Total shares","Cash / Total shares"]', 'Net income / Weighted average shares outstanding', 5, 14),
(a_accounting_adv, 'What is the equity method?', 'multiple_choice', '["Accounting for investments where the investor has significant influence","Recording all investments at cost","Ignoring investments","Only recording dividends received"]', 'Accounting for investments where the investor has significant influence', 5, 15),
(a_accounting_adv, 'SOX compliance requires:', 'multiple_choice', '["Internal controls over financial reporting","Only tax filing","Marketing approvals","Product testing"]', 'Internal controls over financial reporting', 5, 16),
(a_accounting_adv, 'What is activity-based costing?', 'multiple_choice', '["Assigning overhead costs based on activities that drive costs","Allocating costs equally","Ignoring overhead","Using direct costs only"]', 'Assigning overhead costs based on activities that drive costs', 5, 17),
(a_accounting_adv, 'A qualified audit opinion means:', 'multiple_choice', '["Financial statements are fairly presented except for specific issues","Everything is perfect","The company is bankrupt","An adverse finding"]', 'Financial statements are fairly presented except for specific issues', 5, 18),
(a_accounting_adv, 'What is hedging in accounting?', 'multiple_choice', '["Using financial instruments to offset potential losses","Speculating on prices","Avoiding all risk","Increasing leverage"]', 'Using financial instruments to offset potential losses', 5, 19),
(a_accounting_adv, 'Related party disclosures are required to:', 'multiple_choice', '["Ensure transparency about transactions with related parties","Hide company relationships","Reduce tax obligations","Increase revenue"]', 'Ensure transparency about transactions with related parties', 5, 20);

-- BANKING COMPLIANCE (20 questions)  
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, points, order_index) VALUES
(a_banking_compliance, 'The primary purpose of AML regulations is:', 'multiple_choice', '["Prevent the use of the financial system for money laundering","Increase bank profits","Reduce paperwork","Speed up transactions"]', 'Prevent the use of the financial system for money laundering', 5, 1),
(a_banking_compliance, 'What is a Suspicious Activity Report (SAR)?', 'multiple_choice', '["A report filed when a transaction appears suspicious","A daily banking report","A customer complaint","A loan application"]', 'A report filed when a transaction appears suspicious', 5, 2),
(a_banking_compliance, 'CDD stands for:', 'multiple_choice', '["Customer Due Diligence","Cash Deposit Document","Credit Default Derivative","Central Data Directory"]', 'Customer Due Diligence', 5, 3),
(a_banking_compliance, 'What is structuring (smurfing)?', 'multiple_choice', '["Breaking large transactions into smaller ones to avoid reporting","Normal banking activity","Investment strategy","Loan restructuring"]', 'Breaking large transactions into smaller ones to avoid reporting', 5, 4),
(a_banking_compliance, 'PEP stands for:', 'multiple_choice', '["Politically Exposed Person","Personal Economic Profile","Payment Exchange Protocol","Primary Examination Process"]', 'Politically Exposed Person', 5, 5),
(a_banking_compliance, 'The FATF is:', 'multiple_choice', '["An intergovernmental body setting AML/CFT standards","A US federal agency","A bank","An insurance company"]', 'An intergovernmental body setting AML/CFT standards', 5, 6),
(a_banking_compliance, 'What is beneficial ownership?', 'multiple_choice', '["Identifying the individuals who ultimately own or control an entity","Bank account ownership","Property ownership","Stock ownership only"]', 'Identifying the individuals who ultimately own or control an entity', 5, 7),
(a_banking_compliance, 'A risk-based approach to AML means:', 'multiple_choice', '["Allocating resources based on assessed risk levels","Treating all customers equally","Ignoring low-risk customers","Only monitoring high-value transactions"]', 'Allocating resources based on assessed risk levels', 5, 8),
(a_banking_compliance, 'What is trade-based money laundering?', 'multiple_choice', '["Using international trade transactions to move value and disguise illicit origins","Normal trade financing","Currency exchange","Stock trading"]', 'Using international trade transactions to move value and disguise illicit origins', 5, 9),
(a_banking_compliance, 'Enhanced due diligence is required for:', 'multiple_choice', '["Higher-risk customers, PEPs, and complex transactions","All customers equally","Only new customers","Only domestic customers"]', 'Higher-risk customers, PEPs, and complex transactions', 5, 10),
(a_banking_compliance, 'What is sanctions screening?', 'multiple_choice', '["Checking customers against lists of sanctioned individuals and entities","Marketing screening","Credit scoring","Performance review"]', 'Checking customers against lists of sanctioned individuals and entities', 5, 11),
(a_banking_compliance, 'The three stages of money laundering are:', 'multiple_choice', '["Placement, Layering, Integration","Deposit, Transfer, Withdraw","Open, Manage, Close","Apply, Approve, Disburse"]', 'Placement, Layering, Integration', 5, 12),
(a_banking_compliance, 'What is a Currency Transaction Report (CTR)?', 'multiple_choice', '["A report filed for cash transactions above a threshold","A foreign exchange report","A loan document","A deposit receipt"]', 'A report filed for cash transactions above a threshold', 5, 13),
(a_banking_compliance, 'Compliance training for bank staff should:', 'multiple_choice', '["Be ongoing, role-specific, and include real-world scenarios","Be done once only","Be optional","Only cover sales techniques"]', 'Be ongoing, role-specific, and include real-world scenarios', 5, 14),
(a_banking_compliance, 'What is de-risking in banking?', 'multiple_choice', '["Terminating relationships with customers perceived as high-risk","Increasing risk exposure","Adding new products","Expanding to new markets"]', 'Terminating relationships with customers perceived as high-risk', 5, 15),
(a_banking_compliance, 'CFT stands for:', 'multiple_choice', '["Combating the Financing of Terrorism","Cash Flow Tracking","Corporate Financial Transparency","Central Fund Transfer"]', 'Combating the Financing of Terrorism', 5, 16),
(a_banking_compliance, 'What is transaction monitoring?', 'multiple_choice', '["Automated surveillance of transactions for suspicious patterns","Manual counting of cash","Customer satisfaction surveys","Marketing analytics"]', 'Automated surveillance of transactions for suspicious patterns', 5, 17),
(a_banking_compliance, 'A compliance officer is responsible for:', 'multiple_choice', '["Ensuring the bank adheres to all regulatory requirements","Only marketing","Only sales","Only IT"]', 'Ensuring the bank adheres to all regulatory requirements', 5, 18),
(a_banking_compliance, 'What is correspondent banking?', 'multiple_choice', '["A bank providing services on behalf of another bank, often cross-border","Email banking","Mobile banking","Online banking"]', 'A bank providing services on behalf of another bank, often cross-border', 5, 19),
(a_banking_compliance, 'Record retention requirements typically mandate:', 'multiple_choice', '["Keeping records for at least 5 years after the relationship ends","Deleting records immediately","Keeping records for 1 month","No specific requirement"]', 'Keeping records for at least 5 years after the relationship ends', 5, 20);

-- B2B SALES (20 questions)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, points, order_index) VALUES
(a_sales_b2b, 'Enterprise sales cycles are typically:', 'multiple_choice', '["Longer and involve multiple decision-makers","Very short","One-call closes","Impulse purchases"]', 'Longer and involve multiple decision-makers', 5, 1),
(a_sales_b2b, 'What is Account-Based Marketing (ABM)?', 'multiple_choice', '["Targeting specific high-value accounts with personalized campaigns","Mass marketing","Cold calling everyone","Generic email blasts"]', 'Targeting specific high-value accounts with personalized campaigns', 5, 2),
(a_sales_b2b, 'MEDDIC is a:', 'multiple_choice', '["B2B sales qualification framework","Medical procedure","Marketing tool","Financial model"]', 'B2B sales qualification framework', 5, 3),
(a_sales_b2b, 'What is solution selling?', 'multiple_choice', '["Focusing on customer problems and tailoring solutions","Pushing products regardless of need","Discounting heavily","Feature dumping"]', 'Focusing on customer problems and tailoring solutions', 5, 4),
(a_sales_b2b, 'A sales champion is:', 'multiple_choice', '["An internal advocate within the prospect''s organization","The sales manager","A competitor","A customer support rep"]', 'An internal advocate within the prospect''s organization', 5, 5),
(a_sales_b2b, 'What is a Request for Proposal (RFP)?', 'multiple_choice', '["A formal document requesting vendors to submit proposals","A purchase order","An invoice","A complaint"]', 'A formal document requesting vendors to submit proposals', 5, 6),
(a_sales_b2b, 'Annual Recurring Revenue (ARR) is:', 'multiple_choice', '["Yearly value of subscription or recurring revenue","One-time sales total","Marketing budget","Operating expenses"]', 'Yearly value of subscription or recurring revenue', 5, 7),
(a_sales_b2b, 'What is multi-threading in sales?', 'multiple_choice', '["Building relationships with multiple stakeholders in an account","Using multiple phones","Sending many emails","Working multiple jobs"]', 'Building relationships with multiple stakeholders in an account', 5, 8),
(a_sales_b2b, 'A proof of concept (POC) demonstrates:', 'multiple_choice', '["That the solution can work in the client''s environment","Financial returns","Legal compliance","Market share"]', 'That the solution can work in the client''s environment', 5, 9),
(a_sales_b2b, 'What is the Challenger Sale methodology?', 'multiple_choice', '["Teaching, tailoring, and taking control of conversations","Always agreeing with the customer","Never pushing back","Only relationship building"]', 'Teaching, tailoring, and taking control of conversations', 5, 10),
(a_sales_b2b, 'Sales forecasting helps with:', 'multiple_choice', '["Predicting future revenue and planning resources","Historical analysis only","Customer satisfaction","Product development"]', 'Predicting future revenue and planning resources', 5, 11),
(a_sales_b2b, 'What is a mutual action plan?', 'multiple_choice', '["A shared timeline between buyer and seller for closing a deal","A legal contract","A marketing plan","An internal memo"]', 'A shared timeline between buyer and seller for closing a deal', 5, 12),
(a_sales_b2b, 'Total Contract Value (TCV) includes:', 'multiple_choice', '["All revenue from a contract including one-time and recurring","Only monthly payments","Only the first year","Only discounts"]', 'All revenue from a contract including one-time and recurring', 5, 13),
(a_sales_b2b, 'Discovery calls are used to:', 'multiple_choice', '["Understand the prospect''s needs, challenges, and goals","Immediately pitch the product","Close the deal","Send a proposal"]', 'Understand the prospect''s needs, challenges, and goals', 5, 14),
(a_sales_b2b, 'What is competitive displacement?', 'multiple_choice', '["Replacing a competitor''s product in an existing account","Copying competitors","Lowering prices only","Negative marketing"]', 'Replacing a competitor''s product in an existing account', 5, 15),
(a_sales_b2b, 'Win rate measures:', 'multiple_choice', '["Percentage of deals won out of total opportunities","Total revenue","Number of calls made","Customer satisfaction"]', 'Percentage of deals won out of total opportunities', 5, 16),
(a_sales_b2b, 'What is a buying committee?', 'multiple_choice', '["Group of stakeholders involved in the purchase decision","A sales team","A marketing department","An external agency"]', 'Group of stakeholders involved in the purchase decision', 5, 17),
(a_sales_b2b, 'Strategic partnerships in B2B involve:', 'multiple_choice', '["Long-term alliances for mutual growth and market access","One-time transactions","Vendor-only relationships","Competitor agreements"]', 'Long-term alliances for mutual growth and market access', 5, 18),
(a_sales_b2b, 'Customer success in B2B focuses on:', 'multiple_choice', '["Ensuring customers achieve desired outcomes with the product","Only renewals","Only support tickets","Only billing"]', 'Ensuring customers achieve desired outcomes with the product', 5, 19),
(a_sales_b2b, 'What is expansion revenue?', 'multiple_choice', '["Additional revenue from existing customers through upsells and cross-sells","Revenue from new customers only","Marketing spend","Cost reductions"]', 'Additional revenue from existing customers through upsells and cross-sells', 5, 20);

-- DATA ENGINEERING (20 questions)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, points, order_index) VALUES
(a_data_engineer, 'Apache Kafka is primarily used for:', 'multiple_choice', '["Real-time data streaming and event processing","Static file storage","Image processing","User authentication"]', 'Real-time data streaming and event processing', 5, 1),
(a_data_engineer, 'What is a data lake?', 'multiple_choice', '["A centralized repository for storing raw data in various formats","A type of database","A backup system","A data visualization tool"]', 'A centralized repository for storing raw data in various formats', 5, 2),
(a_data_engineer, 'Star schema in data warehousing consists of:', 'multiple_choice', '["Fact tables surrounded by dimension tables","Only fact tables","Only dimension tables","Random tables"]', 'Fact tables surrounded by dimension tables', 5, 3),
(a_data_engineer, 'What is Apache Spark?', 'multiple_choice', '["A unified analytics engine for large-scale data processing","A database","A web framework","An operating system"]', 'A unified analytics engine for large-scale data processing', 5, 4),
(a_data_engineer, 'Data partitioning helps with:', 'multiple_choice', '["Improving query performance by dividing data into manageable chunks","Making data smaller","Deleting old data","Encrypting data"]', 'Improving query performance by dividing data into manageable chunks', 5, 5),
(a_data_engineer, 'What is a data pipeline?', 'multiple_choice', '["A series of processing steps that move data from source to destination","A physical pipe","A network cable","A storage device"]', 'A series of processing steps that move data from source to destination', 5, 6),
(a_data_engineer, 'Apache Airflow is used for:', 'multiple_choice', '["Workflow orchestration and scheduling","Data visualization","Machine learning","Web development"]', 'Workflow orchestration and scheduling', 5, 7),
(a_data_engineer, 'What is schema-on-read?', 'multiple_choice', '["Applying schema when data is read rather than when stored","Defining schema before loading","No schema at all","Schema validation tool"]', 'Applying schema when data is read rather than when stored', 5, 8),
(a_data_engineer, 'Data lineage tracking:', 'multiple_choice', '["Documents the origin, movement, and transformation of data","Counts data rows","Deletes old data","Compresses files"]', 'Documents the origin, movement, and transformation of data', 5, 9),
(a_data_engineer, 'What is a CDC (Change Data Capture)?', 'multiple_choice', '["A technique to identify and capture changes in source data","A disease control center","A data center","A customer data collector"]', 'A technique to identify and capture changes in source data', 5, 10),
(a_data_engineer, 'Columnar storage is optimal for:', 'multiple_choice', '["Analytical queries that read specific columns","Transaction processing","Small datasets","Real-time applications"]', 'Analytical queries that read specific columns', 5, 11),
(a_data_engineer, 'What is data governance?', 'multiple_choice', '["Framework for managing data availability, usability, integrity, and security","Only data backup","Just data deletion","Data visualization"]', 'Framework for managing data availability, usability, integrity, and security', 5, 12),
(a_data_engineer, 'Apache Hadoop consists of:', 'multiple_choice', '["HDFS for storage and MapReduce for processing","Only a database","Only a web server","Only a messaging system"]', 'HDFS for storage and MapReduce for processing', 5, 13),
(a_data_engineer, 'What is data deduplication?', 'multiple_choice', '["Removing duplicate records from datasets","Adding more copies","Encrypting data","Sorting data"]', 'Removing duplicate records from datasets', 5, 14),
(a_data_engineer, 'Batch processing differs from stream processing in that:', 'multiple_choice', '["Batch processes data in groups at intervals; stream processes in real-time","They are the same","Batch is always faster","Stream is always slower"]', 'Batch processes data in groups at intervals; stream processes in real-time', 5, 15),
(a_data_engineer, 'What is a materialized view?', 'multiple_choice', '["A pre-computed query result stored as a table","A virtual table","A temporary table","A view that doesn''t exist"]', 'A pre-computed query result stored as a table', 5, 16),
(a_data_engineer, 'Data quality dimensions include:', 'multiple_choice', '["Accuracy, completeness, consistency, timeliness","Only speed","Only size","Only format"]', 'Accuracy, completeness, consistency, timeliness', 5, 17),
(a_data_engineer, 'What is a medallion architecture?', 'multiple_choice', '["Bronze-Silver-Gold layers for progressive data refinement","A type of database","A security model","A network topology"]', 'Bronze-Silver-Gold layers for progressive data refinement', 5, 18),
(a_data_engineer, 'Idempotency in data pipelines means:', 'multiple_choice', '["Running the same operation multiple times produces the same result","Processing data once only","Never reprocessing data","Random outcomes"]', 'Running the same operation multiple times produces the same result', 5, 19),
(a_data_engineer, 'What is a slowly changing dimension (SCD)?', 'multiple_choice', '["A technique to manage historical changes in dimension data","A fast-changing table","A static table","A temporary table"]', 'A technique to manage historical changes in dimension data', 5, 20);

-- HR TALENT ACQUISITION (20 questions)
INSERT INTO assessment_questions (assessment_id, question_text, question_type, options, correct_answer, points, order_index) VALUES
(a_hr_talent, 'What is employer branding?', 'multiple_choice', '["Promoting a company as an attractive employer to talent","Logo design","Product marketing","Sales branding"]', 'Promoting a company as an attractive employer to talent', 5, 1),
(a_hr_talent, 'A structured interview ensures:', 'multiple_choice', '["Consistency and fairness by using standardized questions","Shorter interviews","Higher salaries","More candidates"]', 'Consistency and fairness by using standardized questions', 5, 2),
(a_hr_talent, 'What is passive recruiting?', 'multiple_choice', '["Engaging candidates who are not actively looking for jobs","Only posting job ads","Waiting for applications","Hiring internally"]', 'Engaging candidates who are not actively looking for jobs', 5, 3),
(a_hr_talent, 'Cost-per-hire includes:', 'multiple_choice', '["Total recruitment costs divided by number of hires","Only job board fees","Only agency fees","Only salary"]', 'Total recruitment costs divided by number of hires', 5, 4),
(a_hr_talent, 'What is a talent pipeline?', 'multiple_choice', '["A pool of qualified candidates ready for future openings","A data pipeline","A sales funnel","A training program"]', 'A pool of qualified candidates ready for future openings', 5, 5),
(a_hr_talent, 'Boolean search in recruiting uses:', 'multiple_choice', '["AND, OR, NOT operators to refine candidate searches","Only keyword matching","Random selection","Alphabetical sorting"]', 'AND, OR, NOT operators to refine candidate searches', 5, 6),
(a_hr_talent, 'What is time-to-fill?', 'multiple_choice', '["Days from job opening to accepted offer","Interview duration","Training time","Probation period"]', 'Days from job opening to accepted offer', 5, 7),
(a_hr_talent, 'Diversity recruiting aims to:', 'multiple_choice', '["Build a workforce reflecting diverse backgrounds and perspectives","Hire only one type of candidate","Reduce headcount","Lower salaries"]', 'Build a workforce reflecting diverse backgrounds and perspectives', 5, 8),
(a_hr_talent, 'What is an ATS?', 'multiple_choice', '["Applicant Tracking System for managing recruitment","Automated Testing System","Annual Training Schedule","Advanced Technology Service"]', 'Applicant Tracking System for managing recruitment', 5, 9),
(a_hr_talent, 'Candidate experience affects:', 'multiple_choice', '["Employer brand, offer acceptance rate, and referrals","Only the candidate","Only the recruiter","Only salary"]', 'Employer brand, offer acceptance rate, and referrals', 5, 10),
(a_hr_talent, 'What is a job competency model?', 'multiple_choice', '["A framework defining skills and behaviors needed for a role","A salary structure","An org chart","A training manual"]', 'A framework defining skills and behaviors needed for a role', 5, 11),
(a_hr_talent, 'Behavioral interview questions typically start with:', 'multiple_choice', '["Tell me about a time when...","What is your salary expectation?","Where do you see yourself in 5 years?","What is your biggest weakness?"]', 'Tell me about a time when...', 5, 12),
(a_hr_talent, 'What is onboarding?', 'multiple_choice', '["The process of integrating new hires into an organization","The firing process","A sales technique","A marketing strategy"]', 'The process of integrating new hires into an organization', 5, 13),
(a_hr_talent, 'Quality of hire measures:', 'multiple_choice', '["Performance, retention, and cultural fit of new hires","Number of applications","Speed of hiring","Cost of job ads"]', 'Performance, retention, and cultural fit of new hires', 5, 14),
(a_hr_talent, 'What is a talent marketplace?', 'multiple_choice', '["A platform connecting internal talent with opportunities within the organization","A physical market","A salary comparison tool","A job board"]', 'A platform connecting internal talent with opportunities within the organization', 5, 15),
(a_hr_talent, 'Reference checks help verify:', 'multiple_choice', '["Past performance, qualifications, and cultural fit","Only identity","Only salary history","Only start date"]', 'Past performance, qualifications, and cultural fit', 5, 16),
(a_hr_talent, 'What is a hiring manager vs. recruiter role?', 'multiple_choice', '["Manager makes the hiring decision; recruiter manages the process","They are the same","Recruiter decides; manager sources","Neither is involved in hiring"]', 'Manager makes the hiring decision; recruiter manages the process', 5, 17),
(a_hr_talent, 'Recruitment marketing includes:', 'multiple_choice', '["Using marketing strategies to attract talent","Only job postings","Only career fairs","Only referrals"]', 'Using marketing strategies to attract talent', 5, 18),
(a_hr_talent, 'What is succession planning?', 'multiple_choice', '["Identifying and developing future leaders for key positions","Planning office relocations","Budget forecasting","Product launches"]', 'Identifying and developing future leaders for key positions', 5, 19),
(a_hr_talent, 'Offer acceptance rate measures:', 'multiple_choice', '["Percentage of offers accepted by candidates","Total offers made","Total applications","Interview count"]', 'Percentage of offers accepted by candidates', 5, 20);

END $$;
